(function(g){var window=this;'use strict';var beb=function(a,b,c){var d;g.J(function(e){switch(e.j){case 1:var f=b;a.W.L("web_player_pt_tt")?(f=g.zr(f).exp||"",f=f.includes("xpv")||f.includes("xpe")):f=!1;if(!f){e.Ha(2);break}if(a.videoData.lw){e.Ha(3);break}g.va(e,4);return g.G(e,a.D.promise,6);case 6:g.wa(e,3);break;case 4:return g.xa(e),e.return();case 3:d={potc:"1",pot:a.videoData.lw},b=g.Ar(b,d);case 2:a.j=g.Ur(b,c),g.ua(e)}})},h3=function(a){a.isActive()||a.start()},ceb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},
deb=function(a,b){var c=new g.sP;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.displayName=a.displayName;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},eeb=function(a,b){var c,d,e;
return g.J(function(f){if(f.j==1)return c=a+"|"+b,g.G(f,g.xu(),2);if(f.j!=3){d=f.B;if(!d)throw g.Tt("gct");return g.G(f,g.KP(d),3)}e=f.B;return f.return(e.get("captions",c))})},feb=function(a,b,c){eeb(a,b).then(function(d){d&&c(d.trackData,new g.sP(d.metadata))})},ieb=function(a){if(!geb.test(a))throw Error("'"+a+"' is not a valid hex color");
a.length==4&&(a=a.replace(heb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},jeb=function(){return g.ct("yt-player-caption-display-settings")},i3=function(){this.segments=[]},keb=function(a,b){var c=g.Yb(a.segments,b);
c>=0||c<0&&(-c-1)%2===1||(c=-c-1,c>0&&b-a.segments[c-1]===1&&c<a.segments.length&&a.segments[c]-b===1?(g.Nb(a.segments,c),g.Nb(a.segments,c-1)):c>0&&b-a.segments[c-1]===1?a.segments[c-1]=b:c<a.segments.length&&a.segments[c]-b===1?a.segments[c]=b:(g.Wb(a.segments,c,0,b),g.Wb(a.segments,c+1,0,b)))},leb=function(a,b,c,d,e,f){g.O.call(this);
this.policy=a;this.player=b;this.qa=c;this.Z=d;this.G=e;this.Y=f;this.D=new i3;this.K=-1;this.C=this.B=this.j=null;this.N=new g.fp(this.h_,1E3,this);this.events=new g.OE(this);g.P(this,this.N);g.P(this,this.events);this.events.T(b,"SEEK_COMPLETE",this.DB);this.DB();this.h_()},meb=function(a){return a.j&&a.j.Mf?a.j.Mf+a.player.Dc()<a.player.getCurrentTime():!1},neb=function(a,b){if(a.policy.eD&&a.policy.Zl&&a.player.Yt()){var c=g.ZM(b,a.policy,{});
c.set("pot",a.player.Yt());c=c.Ce()}else c=g.ZM(b,a.policy,{}).Ce();var d={format:"RAW",withCredentials:!0};if(a.policy.Ka){d.method="POST";var e=b.D;e&&Object.keys(e).length>0?d.postBody=g.CK(e,g.kL):d.postBody=(0,g.WX)([120,0])}a.G&&(d.responseType="arraybuffer");a.C=g.Yr(c,d,3,100).then(function(f){a:{f=f.xhr;a.La();if(a.B){var h=!(a.G?f.response:f.responseText)||f.status>=400,l=g.XHa(f);if(l){f=g.ZM(a.B,a.policy,{});a.B.Fl(f,l);neb(a,a.B);break a}h?a.player.oa("capfail",{status:f.status}):(a.player.Wh().wg("fcb_r"),
l=a.B.gb[0].Pa,a.Z!=null&&a.K!==l&&(h=a.B.gb[0],a.G?a.Z(f.response,(h.startTime+a.player.Dc())*1E3):a.Z(f.responseText,(h.startTime+a.player.Dc())*1E3),a.K=l))}a.B=null;a.C=null}}).Wk(function(f){a.B=null;
a.C=null;var h;a.player.oa("capfail",{status:(h=f.xhr)==null?void 0:h.status})});
a.B=b;keb(a.D,a.B.gb[0].Pa)},j3=function(a,b){g.aU.call(this,b.U());
this.j=a;this.J=b;this.C=null;this.K=!1;this.N=g.MC(this.J.U())&&!this.j.isManifestless},peb=function(a,b){var c=[],d;
for(d in a.j.j)if(a.j.j.hasOwnProperty(d)){var e=a.j.j[d];if(g.yOa(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.J.U().L("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.bcb.get(e);q==null&&(q=oeb[e]||oeb[e.replace(/-/g,"_")],g.bcb.set(e,q));h=q||h}c.push(new g.sP({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
qeb=function(a,b){return b!=null&&b in a.j.j?a.j.j[b]:null},reb=function(a,b,c){var d=[],e;
for(e in a.j.j)if(a.j.j.hasOwnProperty(e)){var f=a.j.j[e];if(g.yOa(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},seb=function(){var a=void 0;
a=a===void 0?{}:a;var b="suggest_correction"in g.ocb?g.ocb.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c={UF:c.UF};c.UF=d;var e=function(f){return function(){return String(a[f.UF])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.UF+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.UF,"gi"),e)}return b},k3=function(a,b,c,d,e,f,h,l,m,n){var p=n.isInline()&&!0,q={};
Object.assign(q,b);Object.assign(q,a.params);Object.assign(q,c);var r={};Object.assign(r,b.Pe);a.params.Pe&&Object.assign(r,a.params.Pe);Object.assign(r,c.Pe);p&&(q.windowOpacity=.6,r.backgroundOpacity=0);q.Pe=r;var t=q.Qi===1,u=[{I:"span",S:"captions-text",X:{style:"word-wrap: normal; display: block;"}}],y,A,D;(l=l.kb("caption_edit_on_hover")&&((y=n.getVideoData().getPlayerResponse())==null?void 0:(A=y.captions)==null?void 0:(D=A.playerCaptionsTracklistRenderer)==null?void 0:D.openTranscriptCommand))&&
u.unshift({I:"button",S:"caption-edit",X:{tabindex:"0","aria-label":seb()},V:[{I:"svg",X:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},V:[{I:"path",X:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.T.call(this,{I:"div",S:"caption-window",X:{id:"caption-window-"+a.id,dir:t?"rtl":"ltr",tabindex:"0",lang:q.lang},V:u});var F=
this;this.K=[];this.Ga=!1;this.B=a;this.Ka=this.Ma=null;this.playerWidth=f;this.playerHeight=h;this.N=null;this.maxWidth=f*.96;this.maxHeight=h*.96;this.j=q;this.yc=c;this.ra=b;this.D=this.Ea("captions-text");this.Ob=this.D.style.getPropertyValue("box-decoration-break")!==""||this.D.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Va=teb(d,e,f,h);this.wc=m;l&&(this.G=this.Ea("caption-edit"),this.T(this.G,"click",function(){F.wc()}));
this.type=0;this.Ya=this.Va*ueb(r);this.Ab=p;a=new g.tT(this.element,!0);g.P(this,a);a.subscribe("dragstart",this.F6,this);a.subscribe("dragmove",this.E6,this);a.subscribe("dragend",this.D6,this);this.fb=this.Xa=this.yb=this.ob=0;a="";this.j.windowOpacity&&(a=ieb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:this.j.isVisible===!1?"none":"","text-align":veb[this.j.textAlign]};this.Ob&&(b["border-radius"]=a?this.Ya/8+"px":"");(this.C=
this.B.params.Qi===2||this.B.params.Qi===3)&&web(this,this.element);g.jm(this.element,b);if(p){var H;(H=this.element.parentElement)==null||H.style.setProperty("--caption-window-color",a)}switch(this.j.Bm){case 0:case 1:case 2:g.np(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.np(this.element,"ytp-caption-window-bottom")}},web=function(a,b){var c="vertical-rl";
a.j.gU===1&&(c="vertical-lr");g.lm&&(c=c==="vertical-lr"?"tb-lr":"tb-rl");g.jm(b,"-o-writing-mode",c);g.jm(b,"-webkit-writing-mode",c);g.jm(b,"writing-mode",c);g.jm(b,"text-orientation","upright");g.np(b,"ytp-vertical-caption");a.B.params.Qi===3&&(g.jm(b,"text-orientation",""),g.jm(b,"transform","rotate(180deg)"))},ueb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(a.offset===0||a.offset===2)b*=.8;return b},xeb=function(a,b){var c={},d=b.background?b.background:a.j.Pe.background;
if(b.backgroundOpacity!=null||b.background){var e=b.backgroundOpacity!=null?b.backgroundOpacity:a.j.Pe.backgroundOpacity;d=ieb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ob&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Ya/8+"px")}if(b.fontSizeIncrement!=null||b.offset!=null)c["font-size"]=a.Va*ueb(b)+"px";d=1;e=b.color||a.j.Pe.color;if(b.color||b.textOpacity!=null)e=ieb(e),d=b.textOpacity==null?a.j.Pe.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;f===0&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.MO&&(h=e=b.MO);var l=a.Va/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=window.devicePixelRatio>=2?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;p<5;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.ks()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;e==null&&(e=a.j.Pe.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}b.fontFamily===7&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]=
"underline");b.U9&&(c.visibility="hidden");b.nZ===1&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.eP||g.Rt,a.B.params.Qi===3?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(b.Yo===1||b.Yo===2||b.Yo===3||b.Yo===4||b.Yo===5)if(g.eP)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Yo){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},l3=function(a){a=a.split("px");
return a.length>0?(a=Number(a[0]))?a:0:0},yeb=function(a){a.N=g.je("SPAN");
g.jm(a.N,{display:"block"});g.np(a.N,"caption-visual-line");a.D.appendChild(a.N)},zeb=function(a,b){var c=g.je("SPAN");
g.jm(c,{display:"inline-block","white-space":"pre-wrap"});g.jm(c,xeb(a,b));c.classList.add("ytp-caption-segment");a.N.appendChild(c);c.previousElementSibling&&(g.jm(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.jm(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Aeb=function(a,b,c){a.Ga=a.Ga||!!c;
var d={};Object.assign(d,a.j.Pe);Object.assign(d,c||b.j);Object.assign(d,a.yc.Pe);(c=!a.N)&&yeb(a);for(var e=a.Ma&&a.Ka&&g.Ec(d,a.Ka)?a.Ma:zeb(a,d),f=typeof b.text==="string",h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=l>0||!b.append,n=h[l];m&&!c?(yeb(a),e=zeb(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.ke(n):n),f||n.tagName!=="RUBY"||n.childElementCount!==4||g.eP||!g.mm(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.mm(n.children[2],"text-emphasis-position")&&(m=
a.C?"padding-left":"padding-bottom"),g.lc?g.jm(e,m,"1em"):g.jm(e,m,"0.5em")))}a.Ka=d;a.Ma=e;a.K.push(b)},teb=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>c*1.3&&(a=480),e=c/a*16);return e},Ceb=function(){this.C=this.time=this.mode=this.B=0;
this.D=new Beb(this);this.G=new Beb(this);this.j=[];this.clear()},Eeb=function(a,b,c){if(a===255&&b===255||!a&&!b)return{Iw:a,
Dt:b,result:0};a=Deb[a];b=Deb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.qe()&&c.Dt===d;if(d)return{Iw:a,Dt:b,result:1}}else if(b&128&&1<=a&&a<=31)return{Iw:a,Dt:b,result:2};return{Iw:a,Dt:b,result:3}},Geb=function(a,b,c,d){b===255&&c===255||!b&&!c?(++a.C===45&&a.reset(),a.D.B.clear(),a.G.B.clear()):(a.C=0,Feb(a.D,b,c,d))},Heb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return h===0?e.order-f.order:h});
for(var c=g.w(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,d.type===0?Geb(a,d.nX,d.oX,b):d.type===1&&a.B&496&&Feb(a.G,d.nX,d.oX,b);a.j.length=0},m3=function(){this.type=0},n3=function(){this.state=this.Dt=this.Iw=0},Zeb=function(){this.timestamp=this.j=0},o3=function(a){this.D=a;
this.B=[];this.j=this.col=this.row=0;this.style=new m3;for(a=this.C=0;a<=15;a++){this.B[a]=[];for(var b=0;b<=32;b++)this.B[a][b]=new Zeb}},p3=function(a,b){if(a.style.type===3){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;m<=15;++m){for(var n=!1,p=d?d:1;p<=32;++p){var q=a.B[m][p];
if(q.j!==0){c===0&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((q.j===0||p===32)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;h<=15;++h)for(l="",m=1;m<=32;++m)if(p=a.B[h][m],q=p.j,q!==0&&(c===0&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),m===32||q===0)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},dfb=function(a,b){switch(a){case 0:return $eb[(b&127)-32];
case 1:return afb[b&15];case 2:return bfb[b&31];case 3:return cfb[b&31]}return 0},q3=function(a){return a.B[a.row][a.col]},r3=function(a,b,c){b>=2&&a.col>1&&(--a.col,q3(a).j=0);
var d=q3(a);d.timestamp=a.D.time+0;d.j=dfb(b,c);a.col<32&&a.col++},efb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;f<=32;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},s3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;e<=32;e++)a.B[b+d][e].reset()},ffb=function(a){a.row=a.j>0?a.j:1;
a.col=1;s3(a,0,15)},gfb=function(a){this.C=a;
this.G=0;this.style=new m3;this.K=new o3(this.C);this.N=new o3(this.C);this.text=new o3(this.C);this.B=this.K;this.D=this.N;this.j=this.B},hfb=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:a.style.get()===4&&d.j>0||(p3(d,c),ffb(a.B),ffb(a.D),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.C.mode=1<<d.C;e?d.col=1:d.j!==b&&(d.j>b?(p3(d,c),s3(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},ifb=function(a){a.style.set(1);
a.j=a.D;a.j.j=0;a.j.style=a.style;a.C.mode=1<<a.j.C},jfb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.C.mode=1<<a.j.C},Beb=function(a){this.j=a;
this.G=0;this.C=new gfb(this.j);this.K=new gfb(this.j);this.B=new n3;this.D=this.C},Feb=function(a,b,c,d){a.B.update();
b=Eeb(b,c,a.B);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Iw;c=b.Dt;if(32<=e||!e)a.j.mode&a.j.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.j,b&96&&r3(a,0,b),c&96&&r3(a,0,c),b!==0&&c!==0&&a.style.type===3&&p3(a,d));else if(e&16)a:if(!a.B.matches(e,c)&&(b=a.B,b.Iw=e,b.Dt=c,b.state=2,b=e&8?a.K:a.C,a.D=b,a.j.mode=1<<(a.G<<2)+(b.G<<1)+(b.style.type===4?1:0),(a.j.mode|1<<(a.G<<2)+(b.G<<1)+(b.style.type!==4?1:0))&a.j.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?((c&14)>>1)*4:0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;efb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,f>0&&(b+=f,e-=f)):(f=f+e-h,f>0&&(e-=f));s3(c,b,e)}}c.row=d;c.col=a+1}else switch(e&7){case 1:switch(c&112){case 32:r3(b.j,0,32);break a;case 48:c===57?(d=b.j,q3(d).j=0,d.col<32&&d.col++):r3(b.j,1,c&15)}break;case 2:c&32&&r3(b.j,2,c&31);break;case 3:c&32&&r3(b.j,3,c&31);break;case 4:case 5:if(32<=c&&c<=47)switch(c){case 32:ifb(b);
break;case 33:d=b.j;d.col>1&&(--d.col,q3(d).j=0);break;case 36:d=b.j;b=q3(d);for(a=0;a<=15;a++)for(c=0;c<=32;c++)if(d.B[a][c]===b){for(;c<=32;c++)d.B[a][c].reset();break}break;case 37:hfb(b,2,d);break;case 38:hfb(b,3,d);break;case 39:hfb(b,4,d);break;case 40:r3(b.j,0,32);break;case 41:b.style.set(2);b.j=b.B;b.j.j=0;b.j.style=b.style;b.C.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);ffb(d);jfb(b);break;case 43:jfb(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:p3(a,
d)}s3(a,0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(a.row<15){++a.row;a.col=1;break b}break;case 3:}a.j<2&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;p3(a,d);efb(a,b,b+1,a.j-1);s3(a,a.row,1)}break;case 46:s3(b.D,0,15);break;case 47:p3(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,ifb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,(d.col+=c&3)>32&&(d.col=32)}}},kfb=function(){},t3=function(a,b,c,d,e,f,h){f=f===void 0?!1:f;
h=h===void 0?null:h;g.qD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},mfb=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(m.fg===1){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=lfb(l.textContent,n.textContent,p.textContent,f.textContent,h);return new t3(a,b,e,c,l,d,m)}switch(m.fg){case 9:case 10:m.Yo=1;break;case 11:m.Yo=2;break;case 12:m.Yo=3;break;case 13:m.Yo=4;break;case 14:m.Yo=5}return new t3(a,b,e,c,l.textContent||"",d,m)},lfb=function(a,b,c,d,e){var f=g.ks(),h=
f?g.je("DIV"):g.je("RUBY"),l=g.je("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.je("DIV"):g.je("RP");a.textContent=b;h.appendChild(a);b=f?g.je("DIV"):g.je("RT");b.textContent=c;h.appendChild(b);c=e.fg;if(c===10||c===11||c===12||c===13||c===14)if(g.jm(b,"text-emphasis-style","filled circle"),g.jm(b,"text-emphasis-color","currentcolor"),g.jm(b,"webkit-text-emphasis","filled circle"),e.fg===11||e.fg===13)g.jm(b,"webkit-text-emphasis-position","under left"),g.jm(b,"text-emphasis-position","under left");c=!0;if(e.fg===4||e.fg===7||e.fg===12||
e.fg===14)g.jm(h,"ruby-position","over"),g.jm(h,"-webkit-ruby-position","before");else if(e.fg===5||e.fg===6||e.fg===11||e.fg===13)g.jm(h,"ruby-position","under"),g.jm(h,"-webkit-ruby-position","after"),c=!1;e=f?g.je("DIV"):g.je("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.jm(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.jm(f,"display","none"),f=f.nextElementSibling,g.jm(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.jm(h.lastElementChild,"display","none"),d?(g.jm(h,"padding-top","0.6em"),g.jm(f,"top","0")):(g.jm(h,"padding-bottom","0.6em"),g.jm(f,"bottom","0")));return h},u3=function(){g.O.apply(this,arguments)},v3=function(a,b,c,d,e){g.qD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},nfb=function(a){var b="_"+w3++;
return new v3(0,0x8000000000000,0,b,a)},x3=function(a){u3.call(this);
this.C=a;this.pens={};this.N={};this.Z={};this.D="_"+w3++;this.K={};this.B=this.j=null;this.G=!0},y3=function(a,b){a=a.getAttribute(b);
if(a!=null)return Number(a)},z3=function(a,b){a=a.getAttribute(b);
if(a!=null)return a==="1"},A3=function(a,b){a=y3(a,b);
return a!==void 0?a:null},C3=function(a,b){a=a.getAttribute(b);
if(a!=null)return B3.test(a),a},ofb=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Z[d]:a.C);a=A3(b,"mh");a!=null&&(c.rB=a);a=A3(b,"ju");a!=null&&(c.textAlign=a);a=A3(b,"pd");a!=null&&(c.Qi=a);a=A3(b,"sd");a!=null&&(c.gU=a);a=C3(b,"wfc");a!=null&&(c.windowColor=a);b=y3(b,"wfo");b!==void 0&&(c.windowOpacity=b/255);return c},pfb=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.N[d]);a=A3(b,"ap");a!=null&&(c.Bm=a);a=y3(b,"cc");a!=null&&(c.Ht=a);a=y3(b,"ah");a!=null&&(c.Fk=a);a=y3(b,"rc");a!=null&&(c.Gs=a);b=y3(b,"av");b!=null&&(c.fp=b);return c},qfb=function(a,b,c,d){var e={};
Object.assign(e,pfb(a,b));Object.assign(e,ofb(a,b));d?g.Ec(e,a.C)?(d=a.D,e=a.C):d="_"+w3++:d=b.getAttribute("id")||"_"+w3++;a=y3(b,"t")+c;b=y3(b,"d")||0x8000000000000;if(e.Qi===2||e.Qi===3)c=e.Gs,e.Gs=e.Ht,e.Ht=c;return new v3(a,b,0,d,e)},D3=function(a){u3.call(this);
this.G=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},E3=function(a){a=g.Dd(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},rfb=function(a,b,c,d,e){d===0&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;a!==void 0&&(f.Gs=a);b=b.ccColCount;b!==void 0&&(f.Ht=b);if(f.Qi===2||f.Qi===3)b=f.Gs,f.Gs=f.Ht,f.Ht=b;return new v3(c,d,0,e,f)},F3=function(a,b,c,d){g.aU.call(this,a);
this.videoData=b;this.audioTrack=c;this.Ua=d;this.G=b.gw},G3=function(a,b,c,d,e,f,h,l,m,n){k3.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},H3=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.G=this.C=this.byteOffset=0;this.j=new DataView(this.trackData);this.B=[]},I3=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},J3=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},K3=function(a,b){u3.call(this);
this.B=a;this.C=b;this.track=this.C.languageName==="CC3"?4:0;this.j=new Ceb;this.j.B=1<<this.track},tfb=function(a){if(typeof a==="string")return!1;
a=new H3(a,8,0);return sfb(a)},sfb=function(a){if(!(a.byteOffset<a.j.byteLength)||J3(a)!==1380139777)return!1;
a.version=I3(a);if(a.version>1)return!1;I3(a);I3(a);I3(a);return!0},L3=function(a,b,c,d,e,f,h,l,m,n){k3.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.Ba=[];this.qa=this.Y=this.Ra=0;this.Fa=NaN;this.Kb=0;this.Tb=null;this.Wa=new g.fp(this.Uba,433,this);this.G&&(n.createClientVe(this.G,this,167342),this.T(this.G,"click",function(){n.logClick(p.G)}),a=new g.tT(this.element,!0),g.P(this,a),a.subscribe("hoverstart",function(){n.logVisibility(p.G,!0)},this));
g.np(this.element,"ytp-caption-window-rollup");g.P(this,this.Wa);g.jm(this.element,"overflow","hidden")},ufb=function(a,b){if(!b)return"";
a.C&&a.B.params.gU!==1&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},vfb=function(a){a.Ba=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.Gs,c=0,d=0,e=a.Ba.length-1;c<b&&e>-1;){var f=a.Ba[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.Y=d;b=Math;c=b.max;isNaN(a.Fa)&&((d=a.j.Ht)?(e=g.je("SPAN"),g.re(e,"\u2013".repeat(d)),g.jm(e,xeb(a,a.j.Pe)),a.D.appendChild(e),a.Fa=e.offsetWidth,a.D.removeChild(e)):a.Fa=0);d=a.D;a.qa=c.call(b,a.Fa,a.Kb,(a.C?d.offsetHeight:d.offsetWidth)+1)},wfb=function(a,b){vfb(a);
var c=a.Ba.reduce(function(f,h){return(a.C?h.offsetWidth:h.offsetHeight)+f},0);
c=a.Y-c;if(c!==a.Ra){var d=c>0&&a.Ra===0,e=c<a.Ra;b||isNaN(c)||d||!e||(g.np(a.element,"ytp-rollup-mode"),g.gp(a.Wa));g.jm(a.D,"transform",ufb(a,c));a.Ra=c}vfb(a)},M3=function(){u3.call(this)},xfb=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(p.nodeType===3)p=new t3(b,c,d,e.id,p.nodeValue,f||n>0,g.Bc(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);xfb(a,b,c,d,e,!0,p,q,m)}}},yfb=function(a){var b=a.split(":");
a=0;b=g.w(b);for(var c=b.next();!c.done;c=b.next())a=a*60+Number(c.value);return a*1E3},zfb=function(a,b,c,d){d=Object.assign({rB:0},d);
return new v3(a,b,c,"_"+w3++,d)},N3=function(a,b){g.O.call(this);
this.J=a;this.W=b;this.j=null;this.B=this.J.qA()},Afb=function(a){if(typeof a==="string"||tfb(a))return a;
var b=new DataView(a);if(b.byteLength<=8||b.getUint32(4)!==1718909296)return"";b=g.dM(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.gK(a)},Cfb=function(a,b,c){if(typeof b==="string"||tfb(b))return[{trackData:b,
aU:c}];var d=new DataView(b);if(d.byteLength<=8||d.getUint32(4)!==1718909296)return[];var e=g.UDa(d);if(a.B&&e){var f=g.MDa(e),h=g.NDa(e);e=e.mj;f&&e&&a.B.fI(e,f,h)}a=g.mM(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.gK(e),f.push({trackData:e,aU:c+h*1E3});Bfb(d,f,c);return f=f.filter(function(l){return!!l.trackData})},Bfb=function(a,b,c){var d=g.dM(a,0,1836476516),e=9E4;
d&&(e=g.eM(d)||9E4);d=0;for(var f=g.mM(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.dM(a,l.dataOffset,1953653094))&&(l=g.dM(a,l.dataOffset,1952867444))&&(l=g.kM(l)/e*1E3,h===0&&(d=l),b[h].aU=l-d+c||c*h*1E3)}},Dfb=function(a,b,c,d,e){if(!tfb(c))throw Error("Invalid binary caption track data");
a.j||(a.j=new K3(e,b));return a.j.Po(c,d)},Efb=function(a,b,c){a.j||(a.j=new M3);
a=a.j.Po(b,c);Math.random()<.01&&g.fx(Error("Deprecated subtitles format in web player: WebVTT"));return a},Gfb=function(a,b,c,d){if(c[0]==="{")try{return a.j||(a.j=new D3(Ffb(b))),a.j.Po(c,d)}catch(f){return g.ex(f),[]}var e=g.Z0(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if(e.firstChild.tagName==="timedtext"){if(Number(e.firstChild.getAttribute("format"))===3)return a.j||(a.j=new x3(Ffb(b),a.W)),a.j.Po(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if(e.firstChild.tagName==="transcript")throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},Ffb=function(a){var b=
{};
if(a=g.vP(a))b.lang=a,g.F$a.test(a)&&(b.Qi=1);return b},O3=function(a){g.XT.call(this,a);
var b=this;this.J=a;this.W=this.J.U();this.videoData=this.J.getVideoData();this.yb=this.J.qb();var c;this.fb=(c=this.J.getVideoData(1))==null?void 0:g.jQ(c);this.C={Pe:{}};this.G={Pe:{}};this.Ga=[];this.Ba={};this.Va={};this.Z=!1;this.Ob=g.YQ(this.videoData);this.Xa=g.zOa(this.videoData,this.J);this.Kb=!!this.videoData.captionTracks.length;this.Tb=!!this.videoData.ze;this.Wa=this.W.controlsType==="3";this.j=this.N=this.Y=this.Ra=this.ob=null;this.Ya=new N3(this.J,this.W);this.B=null;this.qa=new g.OE(this);
this.K=new g.T({I:"div",S:"ytp-caption-window-container",X:{id:"ytp-caption-window-container"}});this.ra={top:0,right:0,bottom:0,left:0,width:1,height:1};c=null;var d=g.Qp("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Hp(d));this.storage=c;var e;this.Jb=!((e=a.Ke())==null||!e.VH());this.D=Hfb(this);this.Fa=!this.D&&this.Wa&&this.Jb&&this.Xa;g.P(this,this.Ya);this.D?this.Ka=this.Ma=null:(this.Ma=new g.ep(this.sU,void 0,this),g.P(this,this.Ma),this.Ka=new g.fp(this.xda,2E3,this),g.P(this,
this.Ka));g.P(this,this.qa);g.GR(this.player,this.K.element,4);g.P(this,this.K);this.qa.T(a,"contentPoTokenReady",this.yG);this.D||this.qa.T(a,"resize",this.uU);(this.Ab=g.NO(this.W)&&!g.Ms()&&!this.J.isFullscreen()&&!this.D&&!this.Fa)&&this.qa.T(a,"resize",this.bba);this.qa.T(a,"onPlaybackAudioChange",this.qaa);this.qa.T(a,g.sD("captions"),function(f){b.onCueRangeEnter(f)});
this.qa.T(a,g.tD("captions"),function(f){b.onCueRangeExit(f)});
this.fb&&this.qa.T(a,"videodatachange",function(f,h){b.onVideoDataChange(f,h)});
Ifb(this,jeb()||{});this.player.Hc("onCaptionsModuleAvailable")},Lfb=function(a){if(a.W.Jb===1||a.videoData.VC===1||g.EQ(a.videoData,"yt:cc")==="alwayson")return!0;
if(a.videoData.captionTracks.length)var b=a.getAudioTrack().B;if(a.W.Jb===2){if(g.bP(a.W))var c=Jfb(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(c!=null)return!!c}c=ceb(a.player.getAudioTrack(),g.bP(a.W));var d=g.EQ(a.videoData,"yt:cc");if(Kfb(a)===void 0){if(c==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return d?d==="on":!0;if(c==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return d==="on"}else return d==="on";return b==="ON"||g.EQ(a.videoData,
"yt:cc")==="on"},P3=function(a,b){if(a.B&&(b===void 0||!b)||!a.videoData.captionTracks.length)return!1;
a=a.getAudioTrack();return!!a.j||a.B==="FORCED_ON"},Kfb=function(a){var b=void 0,c=g.kt(g.it(),65);
if(g.bP(a.W)&&c!=null){if(Jfb(a)!=null)return!1;b=!c}return b},Mfb=function(a){var b;
a.Ob?b=new F3(a.W,a.videoData,a.getAudioTrack(),a.player):a.Xa?b=new j3(a.videoData.j,a.player):a.Kb?b=new g.bU(a.W,a.videoData,a.getAudioTrack()):b=new g.fU(a.W,a.videoData.ze,a.videoData.videoId,g.ULa(a.videoData),a.videoData.An,a.videoData.eventId);return b},R3=function(a,b){if(a.j){if(a.N&&a.N.D)return a.N.D;
g.RQ(a.videoData)&&(b=!0);b||(b=a.Tb?!1:a.Kb?!1:!0);b=b||Nfb(a);b=g.ZT(a.j.B,b);var c=null;if(g.bP(a.W)){var d=a.J.isInline()?void 0:g.ct("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.W.captionsLanguagePreference,g.EQ(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.vP(b[m])===l)return b[m];for(m=0;m<b.length;m++)if(g.vP(b[m]).split("-")[0]===l.split("-")[0])return b[m]}}if(f&&a.j&&(e=a.j.G,
e.length))for(e=g.w(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.W.captionsLanguagePreference,g.EQ(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.vP(b[f])===d[e])return b[f];d=null;a.N&&a.N.C&&(d=a.N.C);d||(d=b.find(function(n){return n.isDefault})||null);
d||(d=b[0]||Q3(a));d&&c&&g.vP(d).split("-")[0]!==c.languageCode.split("-")[0]&&(d=deb(d,c));return d}return null},Q3=function(a){return a.N&&a.N.j},S3=function(a){var b=Q3(a);
return!!b&&a.B===b},Ofb=function(a){var b=ceb(a.player.getAudioTrack(),g.bP(a.W)),c;
b==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?c=R3(a,a.Z):b==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&P3(a)?c=Q3(a):Kfb(a)||a.Z||Lfb(a)?c=R3(a,a.Z):P3(a)&&(c=Q3(a));if(a.D||a.Fa){var d=g.ZT(a.j.B,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.je("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.tP(f));h.setAttribute("srclang",g.vP(f));h.setAttribute("id",f.toString());a.Fa||h.setAttribute("src",a.j.nx(f,"vtt"));f===c&&h.setAttribute("default","1");b.push(h)}c=a.J.Ke();c.hE(b);c=
c.Ib();a.Jb&&a.qa.T(c.textTracks,"change",a.Bca)}else!a.B&&c&&(a.W.L("html5_report_caption_format_intent")&&a.jj(c?c.vssId:"","s"),T3(a,c)),a.player.Hc("onCaptionsTrackListChanged"),a.player.Ai("onApiChange")},Pfb=function(a,b){var c=a.J.Ke().Ib().textTracks;
a=a.B.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?e.mode!=="showing"&&(e.mode="showing"):e.mode==="showing"&&(e.mode="disabled"))}},T3=function(a,b,c){a.loaded&&a.unload();
c!=null&&(a.Z=c,a.Z&&(g.bP(a.W)?U3(a,!!b):V3(a,!!b)));a.W.L("html5_report_caption_format_change")&&(c=a.B,a.Z?c?a.Oj(b,!!b,"m"):b&&a.Oj(b,!0,"m"):!c&&b&&a.Oj(b,!0,"s"));a.B=b;P3(a)&&(a.B=Q3(a));var d;Qfb(a,(d=a.B)!=null?d:void 0);a.load()},Sfb=function(a,b){if(b instanceof v3){var c=a.Ba[b.id];
c&&c.B!==b&&(c.dispose(),delete a.Ba[b.id],c=null);c||(c=Rfb(a,b))&&(a.Ba[b.id]=c)}else c=b.windowId,a.Va[c]||(a.Va[c]=[]),a.Va[c].push(b)},Rfb=function(a,b){var c=Tfb(a);
if(!c)return null;var d=a.B?g.vP(a.B):null;d&&g.F$a.test(d)&&(b.params.Qi=1);var e=a.yb.getPlayerSize();d=e.height*a.ra.height;e=e.width*a.ra.width;a.W.playerStyle!=="google-live"||a.C.isDefault||Object.assign(b.params,a.C);switch(b.params.rB!=null?b.params.rB:b.j.length>1?1:0){case 1:return new G3(b,a.C,a.G,c.width,c.height,e,d,a.W.experiments,a.VN.bind(a),a.J);case 2:return new L3(b,a.C,a.G,c.width,c.height,e,d,a.W.experiments,a.VN.bind(a),a.J);default:return new k3(b,a.C,a.G,c.width,c.height,e,
d,a.W.experiments,a.VN.bind(a),a.J)}},Ifb=function(a,b,c){c=c===void 0?!1:c;
var d=W3.Pe;a.C={};Object.assign(a.C,W3);a.C.Pe={};Object.assign(a.C.Pe,d);a.G={Pe:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;B3.test(f);e.Pe.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;B3.test(f);e.Pe.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||W3.windowColor;B3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;f==null&&(f=d.backgroundOpacity);e.Pe.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;
f==null&&(f=d.fontSizeIncrement);e.Pe.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.C;e=b.fontStyle;e==null&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Pe;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.G:a.C;f=b.textOpacity;f==null&&(f=d.textOpacity);e.Pe.textOpacity=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;f==null&&(f=W3.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;f==null&&(f=d.charEdgeStyle);e.Pe.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;f==null&&(f=d.fontFamily);e.Pe.fontFamily=f;a.loaded&&a.uU();c&&g.bt("yt-player-caption-display-settings",b,2592E3)},Vfb=function(a,b,c){b&&!a.Y?(b=nfb({Qi:0,
lang:"en"}),a.Y=[b,new t3(b.start,b.end-b.start,0,b.id,c!=null?c:"Captions look like this")],a.player.lf(a.Y)):!b&&a.Y&&(Ufb(a,a.Y),a.Y=null)},Ufb=function(a,b){a.player.Wo(b);
b=g.w(b);for(var c=b.next();!c.done;c=b.next())g.Pb(a.Ga,c.value);h3(a.Ma)},Qfb=function(a,b){a.W.L("html5_modify_caption_vss_logging")&&(a.videoData.LD=b)},Tfb=function(a){var b=a.yb.getVideoContentRect(!0).height,c=a.yb.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.ra.height;c*=a.ra.width;return{width:c,height:b}},V3=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},U3=function(a,b){a.J.isInline()||g.bt("yt-player-sticky-caption",b,2592E3)},Jfb=function(a){if(!a.J.isInline())return g.ct("yt-player-sticky-caption")},Hfb=function(a){var b,c=!((b=a.J.Ke())==null||!b.UH());
return a.Wa&&c&&!a.Xa},Nfb=function(a){return a.W.L("web_deprecate_always_includes_asr_setting")&&g.bP(a.W)?!0:!!g.kt(g.it(),66)};
g.PW.prototype.fF=g.ba(51,function(a){var b=2;this.K.has(a)?b=0:g.KUa(this,a)&&(b=1);return b});
g.uZ.prototype.fF=g.ba(50,function(a){return this.bd.fF(a)});
g.PW.prototype.fI=g.ba(49,function(a,b,c){this.Ma.set(a,{Nt:b,Az:c})});
g.uZ.prototype.fI=g.ba(48,function(a,b,c){this.bd.fI(a,b,c)});
g.aU.prototype.OS=g.ba(47,function(){return!1});
g.aU.prototype.Hu=g.ba(46,function(){});
g.bU.prototype.Hu=g.ba(45,function(a,b,c){var d=this;this.La();b=this.nx(a,b);this.Ws();beb(this,b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.fU.prototype.Hu=g.ba(44,function(a,b,c){var d=this;this.La();b=this.nx(a,b);this.Ws();this.j=g.Ur(b,{format:"RAW",onSuccess:function(e){d.j=null;c(e.responseText,a)},
withCredentials:!0})});
g.ET.prototype.Mz=g.ba(43,function(){for(var a=g.be(document,"track",void 0,this.j),b=0;b<a.length;b++)g.pe(a[b])});
g.tW.prototype.Mz=g.ba(42,function(){this.mediaElement.Mz()});
g.ET.prototype.VH=g.ba(41,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.tW.prototype.VH=g.ba(40,function(){return this.mediaElement.VH()});
g.ET.prototype.UH=g.ba(39,function(){return!!this.j.textTracks});
g.tW.prototype.UH=g.ba(38,function(){return this.mediaElement.UH()});
g.ET.prototype.hE=g.ba(37,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.tW.prototype.hE=g.ba(36,function(a){this.mediaElement.hE(a)});
g.yR.prototype.jj=g.ba(34,function(a,b){var c=g.qR(this.app);c&&c.jj(a,b)});
g.KZ.prototype.jj=g.ba(33,function(a,b){a=[a,b];g.JZ(this,g.XI(this.provider),"cfi",a)});
g.XZ.prototype.jj=g.ba(32,function(a,b){this.qoe&&this.qoe.jj(a,b)});
g.r_.prototype.jj=g.ba(31,function(a,b){this.hc().jj(a,b)});
g.yR.prototype.Oj=g.ba(30,function(a,b,c){var d=g.qR(this.app);d&&d.Oj(a,b,c)});
g.KZ.prototype.Oj=g.ba(29,function(a,b,c){if(this.Ra===""||c!=="s")b=[a,b,this.Ra,c],g.JZ(this,g.XI(this.provider),"cfs",b),this.Ra=a});
g.XZ.prototype.Oj=g.ba(28,function(a,b,c){this.qoe&&this.qoe.Oj(a,b,c)});
g.r_.prototype.Oj=g.ba(27,function(a,b,c){this.hc().Oj(a,b,c)});
g.pZ.prototype.tF=g.ba(18,function(){return this.K});
g.C_.prototype.tF=g.ba(17,function(){var a;return((a=g.qR(this))==null?void 0:a.qA())||null});
g.yR.prototype.qA=g.ba(16,function(){return this.app.tF()});
g.r_.prototype.qA=g.ba(15,function(){var a;return((a=this.ya)==null?void 0:a.tF())||null});
g.QL.prototype.jK=g.ba(1,function(a){return(a=this.Tn(a))?a.j:0});
g.pN.prototype.jK=g.ba(0,function(){return 0});
var heb=/#(.)(.)(.)/,geb=/^#(?:[0-9a-f]{3}){1,2}$/i,oeb={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",
la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",
mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",
naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",
or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",
ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",
shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",
sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",
tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",
xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};
i3.prototype.contains=function(a){a=g.Yb(this.segments,a);return a>=0||a<0&&(-a-1)%2===1};
i3.prototype.length=function(){return this.segments.length/2};
g.z(leb,g.O);g.k=leb.prototype;g.k.xa=function(){g.O.prototype.xa.call(this);this.C&&this.C.cancel()};
g.k.DB=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Dc();var b=this.j;this.j=g.Ib(this.qa.Mr(a).gb);b!==this.j&&this.Y&&this.Y()};
g.k.reset=function(){this.D=new i3;this.K=-1;this.C&&(this.C.cancel(),this.C=null)};
g.k.h_=function(){this.La();var a;if(a=this.j!=null)a=this.j,a=a.j.ut(a);if(a&&!this.C&&!(this.j&&this.j.startTime-this.player.getCurrentTime()>30)){a=this.j;a=a.j.vD(a);var b=a.gb[0],c;if((c=this.player.getVideoData())==null?0:c.enableServerStitchedDai)if(c=this.player.qA()){var d=b.j.info.id,e=b.Pa,f=a.gb[0].We;if(this.policy.Ka){if(c=c.nK(f,e,d,3))a.D=c}else if(d=c.iA(f,e,d,3))if(c=c.fF(e),c===0)d&&(a.j=new g.IL(d));else if(c===2){this.N.start();meb(this)&&this.seekTo(this.player.getCurrentTime());
return}}b.j.index.po(b.Pa)?(this.D.contains(a.gb[0].Pa)||neb(this,a),this.j=g.Ib(a.gb)):meb(this)&&this.seekTo(this.player.getCurrentTime())}this.N.start()};
g.z(j3,g.aU);g.k=j3.prototype;g.k.Hu=function(a,b,c){var d=this;this.Ws();b=qeb(this,a.getId());b||(b=a.languageCode,b=this.j.isManifestless?reb(this,b,"386"):reb(this,b));if(b){var e=(b.index.jK(b.index.Vn())-b.index.getStartTime(b.index.Vn()))*1E3,f=new g.uOa(this.W),h=function(){d.C&&d.C.reset();d.K=!0};
this.W.L("html5_keep_caption_data_after_seek")&&(h=null);this.C=new leb(f,this.J,b,function(l,m){c(l,a,m,e)},this.N||g.bF(b.info),h)}};
g.k.OS=function(){var a=this.K;this.K=!1;return a};
g.k.eB=function(a){var b=this.N?[new g.sP({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.sP({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.j.isManifestless?peb(this,"386"):peb(this);b=g.w(b);for(var c=b.next();!c.done;c=b.next())g.$T(this.B,c.value);a()};
g.k.Ws=function(){this.C&&(this.C.dispose(),this.C=null)};
g.k.nx=function(){return""};
var B3=/^#(?:[0-9a-f]{3}){1,2}$/i;var veb=["left","right","center","justify"];g.z(k3,g.T);g.k=k3.prototype;g.k.F6=function(a,b){this.Xa=a;this.fb=b;var c=g.tm(this.element,this.element.parentElement);this.ob=a-c.x;this.yb=b-c.y};
g.k.E6=function(a,b){if(a!==this.Xa||b!==this.fb){g.mp(this.element,"ytp-dragging")||g.np(this.element,"ytp-dragging");var c=g.Am(this.element);a=a-this.ob-.02*this.playerWidth;var d=b-this.yb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.Dd(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.Dd(f,0,2));b=e+f*3;a=(a+e/2*c.width)/this.maxWidth;a=g.Dd(a,0,1)*100;c=(d+f/2*c.height)/this.maxHeight;c=g.Dd(c,0,1)*100;this.B.params.Bm=b;this.B.params.fp=c;this.B.params.Fk=
a;this.B.params.isDefault=!1;this.j.Bm=b;this.j.fp=c;this.j.Fk=a;this.j.isDefault=!1;this.ra.Bm=b;this.ra.fp=c;this.ra.Fk=a;this.ra.isDefault=!1;this.L1()}};
g.k.D6=function(){g.pp(this.element,"ytp-dragging")};
g.k.L1=function(){this.uC(this.K)};
g.k.getType=function(){return this.type};
g.k.uC=function(a){var b=this.Ab?0:Math.min(this.sY(),this.maxWidth),c=this.rY(),d=this.Ab;if(d){var e=getComputedStyle(this.D.parentNode);e=l3(e.borderLeftWidth)+l3(e.borderRightWidth)+l3(e.paddingLeft)+l3(e.paddingRight)}else e=0;var f=e;e="";this.B.params.Qi===3&&(e="rotate(180deg)");var h=d?"calc(96% - "+f+"px)":"96%";g.jm(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":h,"max-height":h,margin:"",transform:""});this.rO(a);e={transform:e,top:"",left:"",
width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var l=this.j.Fk*.96+2;h=this.j.Bm;switch(h){case 0:case 3:case 6:(d=this.j.Pe.fontSizeIncrement)&&d>0&&this.j.Qi!==2&&this.j.Qi!==3&&(l=Math.max(l/(1+d*2),2));e.left=l+"%";break;case 1:case 4:case 7:e.left=l+"%";l=this.D.offsetWidth;b||l?(b=b||l+1,e.width=b+"px",e["margin-left"]=d?b/-2-f/2+"px":b/-2+"px"):e.transform+=" translateX(-50%)";break;case 2:case 5:case 8:e.right=100-l+"%"}d=this.j.fp*.96+2;switch(h){case 0:case 1:case 2:e.top=
d+"%";break;case 3:case 4:case 5:e.top=d+"%";(c=c||this.element.clientHeight)?(e.height=c+"px",e["margin-top"]=c/-2+"px"):e.transform+=" translateY(-50%)";break;case 6:case 7:case 8:e.bottom=100-d+"%"}g.jm(this.element,e);if(this.G){c=this.D.offsetHeight;d=1;for(b=0;b<a.length;b++)e=a[b],typeof e.text==="string"&&(d+=e.text.split("\n").length-1,e.append||b===0||d++);c/=d;this.G.style.height=c+"px";this.G.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+
5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.rO=function(a){var b;for(b=0;b<a.length&&a[b]===this.K[b];b++);if(this.Ga||this.K.length>b)b=0,this.Ga=!1,this.K=[],this.N=this.Ka=this.Ma=null,g.me(this.D);for(;b<a.length;b++)Aeb(this,a[b])};
g.k.sY=function(){return 0};
g.k.rY=function(){return 0};
g.k.toString=function(){return g.T.prototype.toString.call(this)};Ceb.prototype.clear=function(){this.C=this.time=this.mode=0;this.j=[];this.reset()};
Ceb.prototype.reset=function(){this.mode=0;this.D.reset(0);this.G.reset(1)};
var Deb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];m3.prototype.set=function(a){this.type=a};
m3.prototype.get=function(){return this.type};
n3.prototype.clear=function(){this.state=0};
n3.prototype.update=function(){this.state=this.state===2?1:0};
n3.prototype.qe=function(){return this.state!==0};
n3.prototype.matches=function(a,b){return this.qe()&&a===this.Iw&&b===this.Dt};
Zeb.prototype.reset=function(){this.timestamp=this.j=0};
o3.prototype.updateTime=function(a){for(var b=1;b<=15;++b)for(var c=1;c<=32;++c)this.B[b][c].timestamp=a};
o3.prototype.debugString=function(){for(var a="\n",b=1;b<=15;++b){for(var c=1;c<=32;++c){var d=this.B[b][c];a=d.j===0?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
o3.prototype.reset=function(a){for(var b=0;b<=15;b++)for(var c=0;c<=32;c++)this.B[b][c].reset();this.C=a;this.j=0;this.col=this.row=1};
var $eb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],afb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],bfb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],cfb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];gfb.prototype.reset=function(a,b){this.G=b;this.style.set(2);this.B=this.K;this.D=this.N;this.j=this.B;var c=(a<<2)+(b<<1);this.K.reset(c);this.N.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
Beb.prototype.reset=function(a){this.G=a;this.B.clear();this.D=this.C;this.C.reset(a,0);this.K.reset(a,1)};kfb.prototype.D=function(){};g.z(t3,g.qD);t3.prototype.toString=function(){return g.qD.prototype.toString.call(this)};g.z(u3,g.O);u3.prototype.Po=function(){return[]};
u3.prototype.reset=function(){};g.z(v3,g.qD);v3.prototype.toString=function(){return g.qD.prototype.toString.call(this)};
var w3=0;g.z(x3,u3);x3.prototype.reset=function(){this.K={};this.B=this.j=null;this.G=!0};
x3.prototype.Po=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.w(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,c.nodeType===1)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.w(d),a=d.next();!a.done;a=d.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=z3(a,"b");
l!=null&&(h.bold=l);l=z3(a,"i");l!=null&&(h.italic=l);l=z3(a,"u");l!=null&&(h.underline=l);l=A3(a,"et");l!=null&&(h.charEdgeStyle=l);l=A3(a,"of");l!=null&&(h.offset=l);l=C3(a,"bc");l!=null&&(h.background=l);l=C3(a,"ec");l!=null&&(h.MO=l);l=C3(a,"fc");l!=null&&(h.color=l);l=A3(a,"fs");l!=null&&l!==0&&(h.fontFamily=l);l=y3(a,"sz");l!==void 0&&(h.fontSizeIncrement=l/100-1);l=y3(a,"bo");l!==void 0&&(h.backgroundOpacity=l/255);l=y3(a,"fo");l!==void 0&&(h.textOpacity=l/255);l=A3(a,"rb");l!=null&&l!==10&&
l!==0&&(h.fg=l>10?l-1:l);a=A3(a,"hg");a!=null&&(h.nZ=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Z[c]=ofb(this,a);break;case "wp":c=a.getAttribute("id"),this.N[c]=pfb(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.w(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "w":this.j=qfb(this,a,b,!1);(a=this.K[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.K[this.j.id]=this.j;d.push(this.j);break;case "p":var m=a;l=b;c=[];f=m.getAttribute("w")||
this.D;h=!!z3(m,"a");l=(y3(m,"t")||0)+l;var n=y3(m,"d")||5E3;h||(!this.G&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&this.B.text==="\n"&&(this.B.text=""));var p=h?6:5,q=m.getAttribute("p");q=q?this.pens[q]:null;var r=Array.from(m.childNodes);r.length&&(this.G=m.getAttribute("d")!=null);for(m=0;m<r.length;m++){var t=r[m],u=void 0;m>0&&(h=!0);var y=void 0;t.nodeType===1&&(y=t);if(y&&y.tagName==="s"){if((t=(t=y.getAttribute("p"))?this.pens[t]:null)&&t.fg&&(t.fg===1?(t=r.slice(m,
m+4),t.length===4&&(u=mfb(l,n,f,h,p,t,this.pens),m+=3)):u=mfb(l,n,f,h,p,[y],this.pens)),!u){var A=y;u=l;y=n;t=f;var D=h,F=p,H=A.textContent?A.textContent:"",M=A.getAttribute("p");M=M?this.pens[M]:null;A=y3(A,"t")||0;u=new t3(u+A,y-A,F,t,H,D,M)}}else u=new t3(l,n,p,f,t.textContent||"",h,q);c.push(u);this.B=u}if(c.length>0)for(c[0].windowId===this.D&&(this.j=qfb(this,a,b,!0),d.push(this.j)),a=g.w(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var Wfb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.z(D3,u3);D3.prototype.reset=function(){this.B.clear()};
D3.prototype.Po=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.w(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;h!=null&&(f.offset=h);e.szPenSize!==void 0&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;h!=null&&(f.charEdgeStyle=h);e.ecEdgeColor!==void 0&&(f.MO=E3(e.ecEdgeColor));h=e.fsFontStyle;h!=null&&h!==0&&(f.fontFamily=
h);e.fcForeColor!==void 0&&(f.color=E3(e.fcForeColor));e.foForeAlpha!==void 0&&(f.textOpacity=e.foForeAlpha/255);e.bcBackColor!==void 0&&(f.background=E3(e.bcBackColor));e.boBackAlpha!==void 0&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&h!==10&&(f.fg=h>10?h-1:h,f.Yo=Wfb.get(f.fg));e.hgHorizGroup&&(f.nZ=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.w(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.G),e.mhModeHint!==void 0&&(f.rB=e.mhModeHint),e.juJustifCode!==void 0&&(f.textAlign=e.juJustifCode),e.pdPrintDir!==void 0&&(f.Qi=e.pdPrintDir),e.sdScrollDir!==void 0&&(f.gU=e.sdScrollDir),e.wfcWinFillColor!==void 0&&(f.windowColor=E3(e.wfcWinFillColor)),e.wfoWinFillAlpha!==void 0&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.w(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),e.ahHorPos!==
void 0&&(f.Fk=e.ahHorPos),e.apPoint!==void 0&&(f.Bm=e.apPoint),e.avVerPos!==void 0&&(f.fp=e.avVerPos),e.ccCols!==void 0&&(f.Ht=e.ccCols),e.rcRows!==void 0&&(f.Gs=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.w(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;e=(l.tStartMs||0)+b;f=l.dDurationMs||0;if(l.id)h=String(l.id),d=rfb(this,l,e,f,h),a.push(d),this.B.set(h,d);else{l.wWinId?h=l.wWinId.toString():(h="_"+w3++,d=rfb(this,l,e,f,h),a.push(d),this.B.set(h,d));d=a;var m=l;f===0&&(f=5E3);
l=this.B.get(h);var n=!!m.aAppend,p=n?6:5,q=m.segs,r=null;m.pPenId&&(r=this.j.get(m.pPenId));for(m=0;m<q.length;m++){var t=q[m],u=t.utf8;if(u){var y=t.tOffsetMs||0,A=null;t.pPenId&&(A=this.j.get(t.pPenId));if((l.params.rB!=null?l.params.rB:l.j.length>1?1:0)===2&&n&&u==="\n")continue;t=null;var D=[],F;if(F=A&&A.fg===1){F=q;var H=m;if(H+3>=F.length||!F[H+1].pPenId||!F[H+2].pPenId||!F[H+3].pPenId)F=!1;else{var M=F[H+1].pPenId;(M=this.j.get(M))&&M.fg&&M.fg===2?(M=F[H+2].pPenId,M=this.j.get(M),!M||!M.fg||
M.fg<3?F=!1:(M=F[H+3].pPenId,F=(M=this.j.get(M))&&M.fg&&M.fg===2?!0:!1)):F=!1}}if(F)y=q[m+1].utf8,t=q[m+3].utf8,F=q[m+2].utf8,H=this.j.get(q[m+2].pPenId),u=lfb(u,y,F,t,H),t=new t3(e,f,p,h,u,n,A),m+=3;else{if(u.indexOf("<")>-1){var N=void 0;D=A;F=r;H=e;M=f;var Q=y,Z=p,fa=n,pa=[],Y=g.Z0("<html>"+u+"</html>");if(!Y.getElementsByTagName("parsererror").length&&((N=Y.firstChild)==null?0:N.childNodes.length))for(N=g.w(Y.firstChild.childNodes),Y=N.next();!Y.done;Y=N.next()){Y=Y.value;var S=void 0,W=void 0,
v=(W=(S=Y.textContent)==null?void 0:S.replace(/\n/g,""))!=null?W:"";if(Y.nodeType!==3||v&&v.match(/^ *$/)==null){S={};Object.assign(S,D||F);W=void 0;switch((W=Y)==null?void 0:W.tagName){case "b":S.bold=!0;break;case "i":S.italic=!0;break;case "u":S.underline=!0}pa.push(new t3(H+Q,M-Q,Z,l.id,v,fa,S))}}D=pa}D.length||(D=[new t3(e+y,f-y,p,l.id,u,n,A||r)])}if(D.length)for(n=g.w(D),A=n.next();!A.done;A=n.next())A=A.value,d.push(A),l.j.push(A);else t&&(d.push(t),l.j.push(t))}n=!0}}}b=a}else b=[];return b};g.z(F3,g.aU);F3.prototype.Hu=function(a,b,c){feb(this.videoData.videoId,a.vssId,c)};
F3.prototype.eB=function(a){if(this.audioTrack)for(var b=g.w(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.$T(this.B,c.value);a()};g.z(G3,k3);G3.prototype.rO=function(a){var b=this.B.j;k3.prototype.rO.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,Xfb);var e=c.j;var f=d}Aeb(this,c,d)}};
var Xfb={U9:!0};g.z(H3,kfb);H3.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+w3++;c=c/1E3-this.K;d=d/1E3-this.K;a=new v3(c,d-c,5,f,{textAlign:0,Bm:0,Fk:b*2.5,fp:a*5.33});e=new t3(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.z(K3,u3);K3.prototype.Po=function(a){a=new H3(a,a.byteLength,this.B);if(sfb(a)){for(;a.byteOffset<a.j.byteLength;)for(a.version===0?a.C=J3(a)*(1E3/45):a.version===1&&(a.C=J3(a)*4294967296+J3(a)),a.G=I3(a);a.G>0;a.G--){var b=I3(a),c=I3(a),d=I3(a);b&4&&(b&3)===this.track&&(this.track===0||this.track===1)&&(b=this.j,b.j.push({time:a.C,type:this.track,nX:c,oX:d,order:b.j.length}))}Heb(this.j,a);return a.B}return[]};
K3.prototype.reset=function(){this.j.clear()};g.z(L3,k3);g.k=L3.prototype;g.k.L1=function(){g.hp(this.Wa)};
g.k.Uba=function(){g.pp(this.element,"ytp-rollup-mode");this.uC(this.Tb,!0)};
g.k.rY=function(){return this.C?this.qa:this.Y};
g.k.sY=function(){return this.C?this.Y:this.qa};
g.k.uC=function(a,b){this.Tb=a;if(this.B.params.Gs){for(var c=0,d=0;d<this.K.length&&c<a.length;d++)this.K[d]===a[c]&&c++;c>0&&c<a.length&&(a=this.K.concat(a.slice(c)));this.Kb=this.qa;this.Y=this.qa=0;k3.prototype.uC.call(this,a);wfb(this,b)}k3.prototype.uC.call(this,a)};g.z(M3,u3);
M3.prototype.Po=function(a,b){var c=[];a=a.split(Yfb);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(e!==""&&!Zfb.test(e)){var h=$fb.exec(e);if(h&&h.length>=4){var l=yfb(h[1]),m=yfb(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,t="";n=g.w(n);for(var u=n.next();!u.done;u=n.next())if(u=u.value.split(":"),u.length===2){var y=u[1];switch(u[0]){case "line":u=y.split(",");u[0].endsWith("%")&&(p=u[0],h.fp=Number.parseInt(p,10),u.length===2&&(q=u[1].trim()));break;case "position":u=
y.split(",");r=u[0];h.Fk=Number.parseInt(r,10);u.length===2&&(t=u[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.Fk=0;break;case 1:h.Fk=100;break;case 2:h.Fk=50}if(h.textAlign!=null){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(t){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=p<0||p>8?7:p;h.Bm=q}e=e.substring($fb.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=h;h=e;e={};if(h.indexOf("<")<0&&h.indexOf("&")<0)f=zfb(l,m,5,t),m=new t3(l,m,5,f.id,h,!1,g.Bc(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(agb),q.length===1?(h=5,t=zfb(l,m,h,t)):(p=h=6,t=Object.assign({Ht:32},t),t=new v3(l,m,p,"_"+w3++,t)),c.push(t),p=l,r=0;r<q.length;r++)n=q[r],r%2===0?(u=g.Z0("<html>"+n+"</html>"),u.getElementsByTagName("parsererror").length?
(y=u.createElement("span"),y.appendChild(u.createTextNode(n))):y=u.firstChild,xfb(this,p,m-(p-l),h,t,r>0,y,e,c)):p=yfb(n)+f}$fb.lastIndex=0}}return c};
var Zfb=/^NOTE/,Yfb=/(?:\r\n|\r|\n){2,}/,$fb=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),agb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.uW.HK(M3,{Po:"wvppt"});g.z(N3,g.O);
N3.prototype.Po=function(a,b,c,d){c=c||0;d=d||0;if(this.B&&a){a:{var e=d,f=Cfb(this,a,c),h=[];try{for(var l=g.w(f),m=l.next();!m.done;m=l.next()){var n=m.value,p=n.trackData,q=n.aU;h=typeof p!=="string"?h.concat(Dfb(this,b,p,q,e)):p.substring(0,6)==="WEBVTT"?h.concat(Efb(this,p,q)):h.concat(Gfb(this,b,p,q))}var r=h;break a}catch(t){g.ex(t);this.clear();r=[];break a}r=void 0}if(r.length!==0)return r}a=Afb(a);if(!a)return[];try{return typeof a!=="string"?Dfb(this,b,a,c,d):a.substring(0,6)==="WEBVTT"?
Efb(this,a,c):Gfb(this,b,a,c)}catch(t){return g.ex(t),this.clear(),[]}};
N3.prototype.clear=function(){this.j&&this.j.dispose();this.j=null};
N3.prototype.reset=function(){this.j&&this.j.reset()};
N3.prototype.xa=function(){g.O.prototype.xa.call(this);this.clear()};var W3={windowColor:"#080808",windowOpacity:0,textAlign:2,Bm:7,Fk:50,fp:100,isDefault:!0,Pe:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.z(O3,g.XT);g.k=O3.prototype;g.k.xa=function(){if(this.D||this.Fa){var a=this.J.Ke();a&&!a.La()&&a.Mz()}else Vfb(this,!1);g.XT.prototype.xa.call(this)};
g.k.LT=function(){return this.W.L("html5_honor_caption_availabilities_in_audio_track")&&!this.Xa};
g.k.wv=function(){if(this.Wa)return this.D||this.Fa;var a=this.getAudioTrack();if(this.LT()){if(!a.captionTracks.length)return!1;if(!this.j)return!0}a=ceb(a,g.bP(this.W));return a==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:a==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?P3(this):Kfb(this)||P3(this)?!0:Lfb(this)};
g.k.load=function(){var a=this;g.XT.prototype.load.call(this);this.N=this.getAudioTrack();this.j?this.B&&(this.Ya.clear(),this.D?Pfb(this,!0):this.player.getPresentingPlayerType()!==3&&this.j.Hu(this.B,"json3",function(b,c,d,e){if(b){var f;Qfb(a,(f=a.B)!=null?f:void 0);a.j.OS()&&(a.Ga=[],a.J.rf("captions"),h3(a.Ma),a.Ya.reset());if(a.videoData.Rf){var h;d=((h=d)!=null?h:0)+a.videoData.Rf}b=a.Ya.Po(b,c,d,e);if(a.fb)for(c=g.w(b),e=c.next();!e.done;e=c.next())e=e.value,e.C=a.videoData.clientPlaybackNonce,
e.Nl=a.videoData.Rf;c=!a.W.L("html5_keep_caption_data_after_seek")&&a.Xa;a.player.lf(b,void 0,c);!a.Z||a.Fa||S3(a)||!a.W.tm||g.OC(a.W)||g.PO(a.W)||g.hz(a.W)||a.W.Ma==="shortspage"||a.player.isInline()||(g.ip(a.Ka),b=nfb({Bm:0,Fk:5,fp:5,Gs:2,textAlign:0,Qi:0,lang:"en"}),a.Ra=[b],c=["Click "," for settings"],a.ob||(e=new g.Jx(g.cy()),g.P(a,e),a.ob=e.element),e=b.end-b.start,(f=g.tP(a.B))&&a.Ra.push(new t3(b.start,e,0,b.id,f)),a.Ra.push(new t3(b.start,e,0,b.id,c[0]),new t3(b.start,e,0,b.id,a.ob,!0),
new t3(b.start,e,0,b.id,c[1],!0)),a.player.lf(a.Ra),g.gp(a.Ka));!a.Z||a.Fa||S3(a)||(g.bP(a.W)?U3(a,!0):V3(a,!0),a.N&&(a.N.D=a.B),a.player.kp());a.Z=!1}}),this.D||this.Fa||S3(this)||this.player.Hc("captionschanged",g.uP(this.B))):(this.j=Mfb(this),g.P(this,this.j),this.j.eB(function(){Ofb(a)}))};
g.k.unload=function(){this.D&&this.B?Pfb(this,!1):(this.Ka&&g.ip(this.Ka),this.player.rf("captions"),this.Ga=[],this.j&&this.j.Ws(),this.Ya.clear(),this.Y&&this.player.lf(this.Y),this.uU());g.XT.prototype.unload.call(this);this.player.kp();this.player.Hc("captionschanged",{})};
g.k.create=function(){this.wv()&&this.load();var a;a:{var b,c,d;if(this.W.L("web_player_nitrate_promo_tooltip")&&((b=this.videoData.getPlayerResponse())==null?0:(c=b.captions)==null?0:(d=c.playerCaptionsTracklistRenderer)==null?0:d.enableTouchCaptionsNitrate)){var e,f;if(b=(a=this.videoData.getPlayerResponse())==null?void 0:(e=a.captions)==null?void 0:(f=e.playerCaptionsTracklistRenderer)==null?void 0:f.captionTracks)for(a=g.w(b),e=a.next();!e.done;e=a.next())if(e=e.value,e.kind==="asr"&&e.languageCode===
"en"){a=!0;break a}}a=!1}a&&this.J.publish("showpromotooltip",this.K.element)};
g.k.Bca=function(){for(var a=this.J.Ke().Ib().textTracks,b=null,c=0;c<a.length;c++)if(a[c].mode==="showing")a:{b=g.ZT(this.j.B,!0);for(var d=0;d<b.length;d++)if(b[d].toString()===a[c].id){b=b[d];break a}b=null}(this.loaded?this.B:null)!==b&&T3(this,b,!0)};
g.k.bfa=function(){!this.B&&this.D||this.unload()};
g.k.onCueRangeEnter=function(a){this.Ga.push(a);h3(this.Ma)};
g.k.onCueRangeExit=function(a){g.Pb(this.Ga,a);this.j instanceof j3&&this.j.N&&this.player.Wo([a]);h3(this.Ma)};
g.k.getCaptionWindowContainerId=function(){return this.K.element.id};
g.k.xda=function(){Ufb(this,this.Ra);this.Ra=null};
g.k.sU=function(){var a=this;if(!this.Ab||!this.D){this.Ma.stop();g.bba(this.Va);this.Ga.sort(g.rD);var b=this.Ga;if(this.Y){var c=g.kn(b,function(f){return this.Y.indexOf(f)===-1},this);
c.length&&(b=c)}b=g.w(b);for(c=b.next();!c.done;c=b.next())Sfb(this,c.value);b=g.w(Object.entries(this.Ba));var d=b.next();for(c={};!d.done;c={FA:void 0,Ip:void 0},d=b.next()){var e=g.w(d.value);d=e.next().value;e=e.next().value;c.FA=d;c.Ip=e;this.Va[c.FA]?(c.Ip.element.parentNode||(c.Ip instanceof L3||c.Ip instanceof G3||g.tc(this.Ba,function(f){return function(h,l){l!==f.FA&&h.B.params.Bm===f.Ip.B.params.Bm&&h.B.params.Fk===f.Ip.B.params.Fk&&h.B.params.fp===f.Ip.B.params.fp&&(h.dispose(),delete a.Ba[l]);
return l===f.FA}}(c),this),this.K.element.appendChild(c.Ip.element)),c.Ip.uC(this.Va[c.FA])):(c.Ip.dispose(),delete this.Ba[c.FA])}}};
g.k.Dda=function(){Ifb(this,{},!0);this.player.Hc("captionssettingschanged")};
g.k.g9=function(){var a=W3.Pe;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:W3.windowColor,windowOpacity:W3.windowOpacity};var b=jeb()||{};b.background!=null&&(a.background=b.background);b.backgroundOverride!=null&&(a.backgroundOverride=b.backgroundOverride);b.backgroundOpacity!=null&&(a.backgroundOpacity=
b.backgroundOpacity);b.backgroundOpacityOverride!=null&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);b.charEdgeStyle!=null&&(a.charEdgeStyle=b.charEdgeStyle);b.charEdgeStyleOverride!=null&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);b.color!=null&&(a.color=b.color);b.colorOverride!=null&&(a.colorOverride=b.colorOverride);b.fontFamily!=null&&(a.fontFamily=b.fontFamily);b.fontFamilyOverride!=null&&(a.fontFamilyOverride=b.fontFamilyOverride);b.fontSizeIncrement!=null&&(a.fontSizeIncrement=
b.fontSizeIncrement);b.fontSizeIncrementOverride!=null&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);b.fontStyle!=null&&(a.fontStyle=b.fontStyle);b.fontStyleOverride!=null&&(a.fontStyleOverride=b.fontStyleOverride);b.textOpacity!=null&&(a.textOpacity=b.textOpacity);b.textOpacityOverride!=null&&(a.textOpacityOverride=b.textOpacityOverride);b.windowColor!=null&&(a.windowColor=b.windowColor);b.windowColorOverride!=null&&(a.windowColorOverride=b.windowColorOverride);b.windowOpacity!=null&&
(a.windowOpacity=b.windowOpacity);b.windowOpacityOverride!=null&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.B3=function(a,b){var c={};Object.assign(c,jeb());Object.assign(c,a);Ifb(this,c,b);this.player.Hc("captionssettingschanged")};
g.k.uU=function(){!this.D&&this.loaded&&(g.qc(this.Ba,function(a,b){a.dispose();delete this.Ba[b]},this),this.sU())};
g.k.Uh=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Dd(b,-2,4);this.B3({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&T3(this,this.B,!0);break;case "stickyLoading":b!==void 0&&this.W.N&&(g.bP(this.W)?U3(this,!!b):V3(this,!!b));break;case "track":if(!this.j)return{};if(b){this.W.L("html5_report_caption_format_intent")&&this.jj(g.Bc(b)?"":b.vss_id,"m");if(this.D)break;if(!g.Qa(b))break;if(g.Bc(b)){T3(this,null,!0);break}a=g.ZT(this.j.B,!0);for(var d=0;d<a.length;d++){var e=
a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||(e.captionId||"")!==(b.captionId||"")||g.tP(e)!==b.displayName)||(c=b.translationLanguage?deb(e,b.translationLanguage):e)}this.bN(b.position);!c||c===this.B&&this.loaded||(b=g.eL(),a=g.vP(c),b.length&&a===b[b.length-1]||(b.push(a),g.bt("yt-player-caption-language-preferences",b)),g.bP(this.W)&&!this.J.isInline()&&g.bt("yt-player-caption-sticky-language",a,2592E3),T3(this,c,!0))}else return this.loaded&&this.B&&!S3(this)?g.uP(this.B):
{};return"";case "tracklist":return this.j?g.Al(g.ZT(this.j.B,!(!b||!b.includeAsr)),function(f){return g.uP(f)}):[];
case "translationLanguages":return this.j?this.j.G.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.D||b===void 0||Vfb(this,!!b);break;case "sampleSubtitlesCustomized":this.D||Vfb(this,!!b,b);break;case "recommendedTranslationLanguages":return g.eL();case "defaultTranslationSourceTrackIndices":return this.j?this.j.Z:[]}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.W.N&&a.push("stickyLoading");return a};
g.k.Nr=function(){var a=this.B;if(this.W.L("html5_cue_ranges_based_caption_vss")&&!this.J.vK("captions"))return{};if(this.W.L("html5_modify_caption_vss_logging")){var b;return(a=(b=this.videoData.LD)!=null?b:null)?{cc:g.gKa(a)}:{}}return a?(b=a.vssId,a.translationLanguage&&b&&(b="t"+b+"."+g.vP(a)),{cc:b}):{}};
g.k.Nea=function(){this.isSubtitlesOn()?(this.W.L("html5_report_caption_format_intent")&&this.jj("","m"),g.bP(this.W)?U3(this,!1):V3(this,!1),Qfb(this),this.W.L("html5_report_caption_format_change")?T3(this,null,!0):(this.unload(),P3(this,!0)&&T3(this,Q3(this),!1))):this.X2()};
g.k.X2=function(){if(this.W.L("html5_report_caption_format_intent")){var a=S3(this)||!this.B?R3(this,!0):this.B;this.jj(a?a.vssId:"","m")}this.isSubtitlesOn()||T3(this,S3(this)||!this.B?R3(this,!0):this.B,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.B&&!S3(this)};
g.k.yG=function(){this.j&&this.j.yG()};
g.k.qaa=function(){var a=S3(this);P3(this,a)?T3(this,this.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.LT()&&(this.Z=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null)),this.wv()&&(a?T3(this,R3(this),!1):this.load()))};
g.k.bN=function(a){a&&(this.ra={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.K.element.style.top=this.ra.top*100+"%",this.K.element.style.left=this.ra.left*100+"%",this.K.element.style.width=this.ra.width*100+"%",this.K.element.style.height=this.ra.height*100+"%",this.K.element.style.position="absolute",a=Tfb(this))&&(this.K.element.style.width=a.width+"px",this.K.element.style.height=a.height+"px")};
g.k.onVideoDataChange=function(a,b){a==="newdata"&&(this.videoData=b,this.loaded&&this.unload(),this.Z=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null,this.player.Hc("captionschanged",{})),this.wv()&&this.load())};
g.k.getAudioTrack=function(){return this.fb&&this.player.getPresentingPlayerType()===2?this.videoData.bl:this.player.getAudioTrack()};
g.k.bba=function(){var a=this.J.Ke();a&&!a.La()&&a.Mz();this.J.isFullscreen()?(this.D=this.Wa=!0,this.loaded&&Ofb(this)):(this.Wa=this.W.controlsType==="3",this.D=Hfb(this));T3(this,this.B)};
g.k.VN=function(){var a,b,c,d=(a=this.videoData.getPlayerResponse())==null?void 0:(b=a.captions)==null?void 0:(c=b.playerCaptionsTracklistRenderer)==null?void 0:c.openTranscriptCommand;d&&this.player.ib("innertubeCommand",d)};
g.k.Oj=function(a,b,c){var d=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,e="";a&&(e=a.vssId,e=e.replace(d,""));var f="";a&&a.getId()&&(f=a.getId()||"",f=f.replace(d,""));a&&a.getXtags()&&(a=a.getXtags(),a=a.replace(d,""),f=f.concat(";"+a));this.J.Oj(b?e:"",b?f:"",c)};
g.k.jj=function(a,b){a=(a||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");this.J.jj(a,b)};
g.uW.HK(O3,{sU:"smucd"});g.WT("captions",O3);})(_yt_player);
