(function(g){var window=this;'use strict';var Sib=function(a,b){a.ib("onAutonavCoundownStarted",b)},i5=function(a,b,c){g.rp(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.gh(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.DP&&(b.lengthText?(e=b.lengthText||null,f=b.Mx||null):b.lengthSeconds&&(e=g.Zy(b.lengthSeconds),f=g.Zy(b.lengthSeconds,!0)));var h=!!d;d=h&&g.BP(d).type==="RD";var l=b instanceof g.DP?b.isLivePlayback:null,m=b instanceof g.DP?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.DD("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.El(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.Ct};b instanceof g.CP&&(c.playlist_length=b.playlistLength);a.update(c)},j5=function(a){var b=a.U(),c=b.D;
g.T.call(this,{I:"a",S:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",Na:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},V:[{I:"div",X:{"aria-label":"{{timestamp}}"},Na:["ytp-autonav-timestamp"],va:"{{duration}}"},{I:"div",Na:["ytp-autonav-live-stamp"],va:"Live"},{I:"div",
Na:["ytp-autonav-upcoming-stamp"],va:"Upcoming"},{I:"div",S:"ytp-autonav-list-overlay",V:[{I:"div",S:"ytp-autonav-mix-text",va:"Mix"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",Na:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],va:"{{title}}"},{I:"div",Na:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],va:"{{author}}"},{I:"div",Na:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],va:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.j=c;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},k5=function(a,b){b=b===void 0?!1:b;
g.T.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.K=b;this.cancelCommand=this.G=void 0;this.C=0;this.container=new g.T({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.P(this,this.container);this.container.Ja(this.element);b=a.U();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.T({I:"div",S:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",va:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.Y:""},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",X:{style:"{{background}}"},V:[{I:"div",X:{"aria-label":"{{timestamp}}"},Na:["ytp-autonav-timestamp"],
va:"{{duration}}"},{I:"div",Na:["ytp-autonav-live-stamp"],va:"Live"},{I:"div",Na:["ytp-autonav-upcoming-stamp"],va:"Upcoming"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",V:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",va:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",va:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",va:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",va:"{{author_and_views}}"}]}]}]});
g.P(this,this.j);this.j.Ja(this.container.element);d||this.T(this.j.Ea("ytp-autonav-endscreen-link-container"),"click",this.TU);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.j.Ea("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.T({I:"div",S:"ytp-autonav-overlay"});g.P(this,this.overlay);this.overlay.Ja(this.container.element);this.B=new g.T({I:"div",S:"ytp-autonav-endscreen-button-container"});g.P(this,this.B);this.B.Ja(this.container.element);
this.cancelButton=new g.T({I:"button",Na:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"Cancel autoplay"},va:"Cancel"});g.P(this,this.cancelButton);this.cancelButton.Ja(this.B.element);this.cancelButton.listen("click",this.H4,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.T({I:"a",Na:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"Play next video"},va:"Play Now"});g.P(this,this.playButton);this.playButton.Ja(this.B.element);this.playButton.listen("click",this.TU,this);this.J.L("web_player_autonav_next_button_renderer")?(this.J.createServerVe(this.playButton.element,this.playButton,!0),(b=this.J.getVideoData())&&Tib(this,b)):this.J.createClientVe(this.playButton.element,this,115130);this.D=new g.fp(function(){Uib(c)},
500);
g.P(this,this.D);this.SU();this.T(a,"autonavvisibility",this.SU);this.J.L("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.G4),this.T(a,"onAutonavCoundownStarted",this.raa))},l5=function(a){var b=a.J.Zn(!0,a.J.isFullscreen());
g.rp(a.container.element,"ytp-autonav-endscreen-small-mode",a.Og(b));g.rp(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.GM);g.rp(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.Df());g.rp(a.J.getRootNode(),"countdown-running",a.Il());g.rp(a.container.element,"ytp-player-content",a.J.Df());g.jm(a.overlay.element,{width:b.width+"px"});if(!a.Il()){a.J.Df()?Vib(a,Math.round(Wib(a)/1E3)):Vib(a);b=!!a.suggestion&&!!a.suggestion.Ct;var c=a.J.Df()||!b;
g.rp(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.rp(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.Mx(a.B,a.J.Df());g.rp(a.element,"ytp-enable-w2w-color-transitions",Xib(a))}},Uib=function(a){var b=Wib(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);Vib(a,Math.ceil((b-c)/1E3));b-c<=500&&a.Il()?a.select(!0):a.Il()&&a.D.start()},Wib=function(a){if(a.J.isFullscreen()){var b;
a=(b=a.J.getVideoData())==null?void 0:b.DD;return a===-1||a===void 0?8E3:a}return a.J.Tt()>=0?a.J.Tt():g.AC(a.J.U().experiments,"autoplay_time")||1E4},Tib=function(a,b){a.J.L("web_player_autonav_next_button_renderer");
b=b.xfa;a.G=b==null?void 0:b.navigationEndpoint;b=b==null?void 0:b.trackingParams;a.playButton&&b&&a.J.setTrackingParams(a.playButton.element,b)},Xib=function(a){var b;
return!((b=a.J.getVideoData())==null||!b.watchToWatchTransitionRenderer)},Vib=function(a,b){b=b===void 0?-1:b;
a=a.j.Ea("ytp-autonav-endscreen-upnext-header");g.me(a);if(b>=0){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(d>=0){a.appendChild(g.ke("Up next in $SECONDS".slice(0,d)));var e=g.je("span");g.lp(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.re(e,b);a.appendChild(e);a.appendChild(g.ke("Up next in $SECONDS".slice(d+c.length)));return}}g.re(a,"Up next")},m5=function(a,b){g.T.call(this,{I:"div",
Na:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},n5=function(a){g.T.call(this,{I:"div",
Na:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},V:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",V:[{I:"span",S:"ytp-upnext-header",va:"Up Next"},{I:"span",S:"ytp-upnext-title",va:"{{title}}"},{I:"span",S:"ytp-upnext-author",va:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"Play next video"},V:[{I:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
V:[{I:"circle",S:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",V:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
va:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.G=this.Ea("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.fp(this.nJ,5E3,this);this.B=0;var b=this.Ea("ytp-upnext-cancel");this.cancelButton=new g.T({I:"button",Na:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"Cancel autoplay"},va:"Cancel"});g.P(this,this.cancelButton);this.cancelButton.listen("click",this.I4,this);this.cancelButton.Ja(b);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.P(this,this.D);this.api.createClientVe(this.element,this,18788);b=this.Ea("ytp-upnext-autoplay-icon");this.T(b,"click",this.J4);this.api.createClientVe(b,this,115130);this.UU();this.T(a,"autonavvisibility",this.UU);this.T(a,"mdxnowautoplaying",this.dba);this.T(a,"mdxautoplaycanceled",this.eba);g.rp(this.element,"ytp-upnext-mobile",this.api.U().B)},Yib=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=(c=a.api.getVideoData())==null?void 0:c.DD;return a===-1||a===void 0?8E3:a}return a.api.Tt()>=0?a.api.Tt():g.AC(a.api.U().experiments,"autoplay_time")||1E4},Zib=function(a,b){b=Yib(a,b);
var c=Math,d=c.min;var e=(0,g.Zt)()-a.B;c=d.call(c,e,b);b=b===0?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));b>=1&&a.Il()&&a.api.getPresentingPlayerType()!==3?a.select(!0):a.Il()&&a.j.start()},o5=function(a){m5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.T({I:"div",S:"ytp-suggestion-panel",V:[{I:"div",Na:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],va:"More videos"}]});this.N=new g.T({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new k5(this.player);g.P(this,this.B);this.B.Ja(this.element);a.getVideoData().Sf?this.j=this.B:(this.j=new n5(a),g.GR(this.player,this.j.element,4),g.P(this,this.j));this.overlay=new g.T({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.P(this,this.overlay);this.overlay.Ja(this.element);this.D=new g.OE(this);g.P(this,this.D);g.P(this,this.table);this.table.Ja(this.element);this.table.show();g.P(this,this.N);this.N.Ja(this.table.element);this.hide()},p5=function(a){var b=a.Df();
b!==a.G&&(a.G=b,a.player.publish("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},q5=function(a,b){g.T.call(this,{I:"button",
Na:["ytp-watch-on-youtube-button","ytp-button"],va:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.m2();this.buttonType===2&&g.np(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.m2);g.Mx(this,!0)},r5=function(a,b){m5.call(this,a,"embeds-lite-endscreen");
this.J=a;this.Ne=b;this.J.createClientVe(this.element,this,156943);this.watchButton=new q5(a,2);g.P(this,this.watchButton);this.watchButton.Ja(this.element);this.hide()},$ib=function(a){m5.call(this,a,"subscribecard-endscreen");
this.j=new g.T({I:"div",S:"ytp-subscribe-card",V:[{I:"img",S:"ytp-author-image",X:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",V:[{I:"div",S:"ytp-author-name",va:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.P(this,this.j);this.j.Ja(this.element);var b=a.getVideoData();this.subscribeButton=new g.PU("Subscribe",null,"Unsubscribe",null,!0,!1,b.Wl,b.subscribed,"trailer-endscreen",null,a,!1);g.P(this,this.subscribeButton);this.subscribeButton.Ja(this.j.Ea("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ta);this.Ta();this.hide()},s5=function(a){var b=a.U(),c=g.KE||g.GO?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.T.call(this,{I:"a",Na:e,X:{href:"{{url}}",target:d?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{I:"div",S:"ytp-videowall-still-image",X:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-info-bg",V:[{I:"span",S:"ytp-videowall-still-info-content",X:c,V:[{I:"span",S:"ytp-videowall-still-info-title",va:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",va:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",va:"Live"},{I:"span",S:"ytp-videowall-still-info-duration",va:"{{duration}}"}]}]}]},{I:"span",Na:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",S:"ytp-videowall-still-listlabel-length",V:[" (",{I:"span",va:"{{playlist_length}}"},")"]}]},{I:"span",Na:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",S:"ytp-videowall-still-listlabel-length",va:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.OE(this);g.P(this,this.j);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.createServerVe(this.element,this);this.onVideoDataChange()},t5=function(a){m5.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.N=!1;this.Y=null;this.B=new g.OE(this);g.P(this,this.B);this.K=new g.fp(function(){g.np(b.element,"ytp-show-tiles")},0);
g.P(this,this.K);var c=new g.T({I:"button",Na:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"Previous"},V:[g.Tx()]});g.P(this,c);c.Ja(this.element);c.listen("click",this.N4,this);this.table=new g.Jx({I:"div",S:"ytp-endscreen-content"});g.P(this,this.table);this.table.Ja(this.element);c=new g.T({I:"button",Na:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"Next"},V:[g.Ux()]});g.P(this,c);c.Ja(this.element);c.listen("click",this.M4,this);a.getVideoData().Sf?this.j=new k5(a,!0):this.j=
new n5(a);g.P(this,this.j);g.GR(this.player,this.j.element,4);a.createClientVe(this.element,this,158789);this.hide()},u5=function(a){return g.HR(a.player)&&a.kE()&&!a.D},v5=function(a){var b=a.Df();
b!==a.N&&(a.N=b,a.player.publish("autonavvisibility"))},w5=function(a){m5.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new q5(a,1);g.P(this,this.watchButton);this.watchButton.Ja(this.element);g.K8a(a)&&(this.j=new g.a1(a),g.P(this,this.j),this.B=new g.T({I:"div",Na:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},V:[this.j]}),g.P(this,this.B),this.j.Ja(this.B.element),this.B.Ja(this.element));a.createClientVe(this.element,this,156914);this.hide()},djb=function(a){g.XT.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.OE(this);g.P(this,this.listeners);var c=a.U(),d=a.getVideoData();d=d&&d.limitedPlaybackDurationInSeconds!==0;g.Fs(g.RO(c))&&d&&!g.CR(a)?(this.B=!0,this.endScreen=new r5(a,g.nR(a))):a.jd()?this.endScreen=new w5(a):ajb(a)?(this.D=!0,bjb(this),this.j?this.endScreen=new o5(a):this.endScreen=new t5(a)):c.Ig?this.endScreen=new $ib(a):this.endScreen=new m5(a);g.P(this,this.endScreen);g.GR(a,this.endScreen.element,4);cjb(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.sD("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.tD("endscreen"),function(e){b.onCueRangeExit(e)})},bjb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.gm&&a.C===b.Sf)return!1;a.j=b.gm;a.C=b.Sf;return!0},ajb=function(a){a=a.U();
return a.Ed&&!a.Ig},cjb=function(a){a.player.rf("endscreen");
var b=a.player.getVideoData();b=new g.qD(Math.max((b.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.qD(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.lf([b,c])};
g.yR.prototype.Tt=g.ba(14,function(){return this.app.Tt()});
g.C_.prototype.Tt=g.ba(13,function(){return this.getVideoData().kZ});
g.uR.prototype.Ls=g.ba(12,function(a){this.Ji().Ls(a)});
g.dV.prototype.Ls=g.ba(11,function(a){this.j!==a&&(this.j=a,this.Ta())});
g.kW.prototype.Ls=g.ba(10,function(a){this.overflowButton&&this.overflowButton.Ls(a)});
g.uR.prototype.Ms=g.ba(9,function(a){this.Ji().Ms(a)});
g.iV.prototype.Ms=g.ba(8,function(a){this.j!==a&&(this.j=a,this.Ta())});
g.kW.prototype.Ms=g.ba(7,function(a){this.shareButton&&this.shareButton.Ms(a)});
g.uR.prototype.qC=g.ba(6,function(a){this.Ji().qC(a)});
g.IU.prototype.qC=g.ba(5,function(a){this.BS!==a&&(this.BS=a,this.Vq())});
g.uR.prototype.pC=g.ba(4,function(a){this.Ji().pC(a)});
g.kW.prototype.pC=g.ba(3,function(a){this.AS!==a&&(this.AS=a,this.Uq())});g.z(j5,g.T);j5.prototype.select=function(){this.J.qp(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.PE||void 0)&&this.J.logClick(this.element)};
j5.prototype.onClick=function(a){g.xS(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
j5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.z(k5,g.T);g.k=k5.prototype;g.k.tI=function(a){this.suggestion!==a&&(this.suggestion=a,i5(this.j,a),this.playButton.updateValue("url",this.suggestion.El()),l5(this))};
g.k.Il=function(){return this.C>0};
g.k.yC=function(){this.Il()||(this.C=Date.now(),Uib(this),Sib(this.J,Wib(this)),g.rp(this.J.getRootNode(),"countdown-running",this.Il()))};
g.k.wy=function(){this.Oq();Uib(this);var a=this.j.Ea("ytp-autonav-endscreen-upnext-header");a&&g.re(a,"Up next")};
g.k.Oq=function(){this.Il()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,a===void 0?!1:a);this.Oq()};
g.k.TU=function(a){g.xS(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):a.currentTarget===this.j.Ea("ytp-autonav-endscreen-link-container")&&(a=this.j.Ea("ytp-autonav-endscreen-link-container"),this.J.logVisibility(a,!0),this.J.logClick(a)),this.J.L("web_player_autonav_next_button_renderer")&&this.G?(this.J.ib("innertubeCommand",this.G),this.Oq()):this.select())};
g.k.H4=function(){this.J.logClick(this.cancelButton.element);g.AR(this.J,!0);this.cancelCommand&&this.J.ib("innertubeCommand",this.cancelCommand)};
g.k.onVideoDataChange=function(a,b){this.J.L("web_player_autonav_next_button_renderer")&&Tib(this,b);var c;this.cancelCommand=(c=b.wfa)==null?void 0:c.command};
g.k.raa=function(a){if(Xib(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=b==null?void 0:b.fromColorPaletteDark;b=b==null?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.jz(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.jz(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.jz(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.jz(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.jz(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.jz(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.rp(this.element,"ytp-w2w-animate",!0)}};
g.k.G4=function(a){this.J.L("web_autonav_color_transition")&&a!==2&&g.rp(this.element,"ytp-w2w-animate",!1)};
g.k.SU=function(){var a=this.J.Df();this.K&&this.Hb!==a&&g.Mx(this,a);l5(this);this.J.logVisibility(this.container.element,a);this.J.logVisibility(this.cancelButton.element,a);this.J.logVisibility(this.j.Ea("ytp-autonav-endscreen-link-container"),a);this.J.logVisibility(this.playButton.element,a)};
g.k.Og=function(a){return a.width<400||a.height<459};g.z(m5,g.T);g.k=m5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.kE=function(){return!1};
g.k.Df=function(){return!1};
g.k.OZ=function(){return!1};g.z(n5,g.T);g.k=n5.prototype;g.k.nJ=function(){this.notification&&(this.D.stop(),this.Oc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.tI=function(a){this.suggestion=a;i5(this,a,"hqdefault.jpg")};
g.k.UU=function(){g.Mx(this,this.api.Df());this.api.logVisibility(this.element,this.api.Df());this.api.logVisibility(this.Ea("ytp-upnext-autoplay-icon"),this.api.Df());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.Df())};
g.k.oba=function(){window.focus();this.nJ()};
g.k.yC=function(a){var b=this;this.Il()||(g.Iv("a11y-announce","Up Next "+this.suggestion.title),this.B=(0,g.Zt)(),this.j=new g.fp(function(){Zib(b,a)},25),Zib(this,a),Sib(this.api,Yib(this,a)));
g.pp(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.T.prototype.hide.call(this)};
g.k.Il=function(){return!!this.j};
g.k.wy=function(){this.Oq();this.B=(0,g.Zt)();Zib(this);g.np(this.element,"ytp-upnext-autoplay-paused")};
g.k.Oq=function(){this.Il()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=a===void 0?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&typeof document.hasFocus==="function"){var b=Notification.permission;b==="default"?Notification.requestPermission():b!=="granted"||document.hasFocus()||(this.nJ(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.gh()}),this.C=this.T(this.notification,"click",this.oba),this.D.start())}this.Oq();this.api.nextVideo(!1,a)};
g.k.J4=function(a){!g.qe(this.cancelButton.element,a.target)&&g.xS(a,this.api)&&(this.api.Df()&&this.api.logClick(this.Ea("ytp-upnext-autoplay-icon")),this.select())};
g.k.I4=function(){this.api.Df()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.AR(this.api,!0)};
g.k.dba=function(a){this.api.getPresentingPlayerType();this.show();this.yC(a)};
g.k.eba=function(){this.api.getPresentingPlayerType();this.Oq();this.hide()};
g.k.xa=function(){this.Oq();this.nJ();g.T.prototype.xa.call(this)};g.z(o5,m5);g.k=o5.prototype;g.k.create=function(){m5.prototype.create.call(this);this.D.T(this.player,"appresize",this.kD);this.D.T(this.player,"onVideoAreaChange",this.kD);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.VU);this.D.T(this.player,"onAutonavCancelled",this.K4);this.onVideoDataChange()};
g.k.show=function(){m5.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.AR(this.player,!1);g.HR(this.player)&&this.kE()&&!this.C?(p5(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.j.select(!0):this.j.yC():this.videoData.autonavState===3&&this.j.wy()):(g.AR(this.player,!0),p5(this));this.kD()};
g.k.hide=function(){m5.prototype.hide.call(this);this.j.wy();p5(this)};
g.k.kD=function(){var a=this.player.Zn(!0,this.player.isFullscreen());p5(this);l5(this.B);g.rp(this.element,"ytp-autonav-cancelled-small-mode",this.Og(a));g.rp(this.element,"ytp-autonav-cancelled-tiny-mode",this.MK(a));g.rp(this.element,"ytp-autonav-cancelled-mini-mode",a.width<=400||a.height<=360);this.overlay&&g.jm(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.rp(this.videos[a].element,"ytp-suggestion-card-with-margin",a%2===1)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.L("web_player_autonav_empty_suggestions_fix")){var b=g.nQ(this.videoData);b&&(this.j.tI(b),this.j!==this.B&&this.B.tI(b))}if(a&&a.length)for(b=0;b<ejb.length;++b){var c=ejb[b];if(a&&a[c]){this.videos[b]=new j5(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,i5(d,c));g.P(this,this.videos[b]);this.videos[b].Ja(this.N.element)}}this.kD()}};
g.k.VU=function(a){a===1?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Oq(),this.Hb&&this.kD()):(this.K=!0,this.Df()&&(a===2?this.j.yC():a===3&&this.j.wy()))};
g.k.K4=function(a){a?this.VU(1):(this.C=null,this.K=!1)};
g.k.kE=function(){return this.videoData.autonavState!==1};
g.k.Og=function(a){return(a.width<910||a.height<459)&&!this.MK(a)&&!(a.width<=400||a.height<=360)};
g.k.MK=function(a){return a.width<800&&!(a.width<=400||a.height<=360)};
g.k.Df=function(){return this.Hb&&g.HR(this.player)&&this.kE()&&!this.C};
var ejb=[1,3,2,4];g.z(q5,g.T);g.k=q5.prototype;g.k.m2=function(){switch(this.buttonType){case 1:var a="Watch again on YouTube";var b=156915;break;case 2:a="Continue watching on YouTube";b=156942;break;default:a="Continue watching on YouTube",b=156942}this.update({content:a});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,b)};
g.k.onClick=function(a){this.J.L("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.yS(this.getVideoUrl(),this.J,a);this.J.L("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.U();if(g.IO(b)){var c={};g.IO(b)&&g.iR(this.J,"addEmbedsConversionTrackingParams",[c]);if(!this.J.L("embeds_web_enable_referring_feature_deprecation")){a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.ZK(c,b)}a=g.Ti(a,c)}return a};
g.k.logVisibility=function(){this.J.logVisibility(this.element,this.Hb&&this.Z)};
g.k.show=function(){g.T.prototype.show.call(this);this.logVisibility()};
g.k.hide=function(){g.T.prototype.hide.call(this);this.logVisibility()};
g.k.Mc=function(a){g.T.prototype.Mc.call(this,a);this.logVisibility()};g.z(r5,m5);r5.prototype.show=function(){this.player.getPlayerState()!==3&&(m5.prototype.show.call(this),this.Ne.pC(!0),this.Ne.Ms(!0),this.J.U().Ie||this.Ne.Ls(!0),this.J.logVisibility(this.element,!0),this.watchButton.Mc(!0))};
r5.prototype.hide=function(){m5.prototype.hide.call(this);this.Ne.pC(!1);this.Ne.Ms(!1);this.Ne.Ls(!1);this.J.logVisibility(this.element,!1);this.watchButton.Mc(!1)};g.z($ib,m5);$ib.prototype.Ta=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Wl;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.z(s5,g.T);s5.prototype.select=function(){this.api.qp(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.PE||void 0)&&this.api.logClick(this.element)};
s5.prototype.onClick=function(a){if(g.IO(this.api.U())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var b=this.suggestion.El(),c={};g.DR(this.api,c,"emb_rel_end");b=g.Ti(b,c);g.yS(b,this.api,a)}else g.xS(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
s5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
s5.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.B=a.Ff?!1:b.D};g.z(t5,m5);g.k=t5.prototype;g.k.create=function(){m5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.gr();this.B.T(this.player,"appresize",this.gr);this.B.T(this.player,"onVideoAreaChange",this.gr);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.B.T(this.player,"autonavchange",this.nN);this.B.T(this.player,"onAutonavCancelled",this.L4);a=this.videoData.autonavState;a!==this.Y&&this.nN(a);this.B.T(this.element,"transitionend",this.Cca)};
g.k.destroy=function(){g.Ys(this.B);g.gb(this.stills);this.stills=[];m5.prototype.destroy.call(this);g.pp(this.element,"ytp-show-tiles");this.K.stop();this.Y=this.videoData.autonavState};
g.k.kE=function(){return this.videoData.autonavState!==1};
g.k.show=function(){var a=this.Hb;m5.prototype.show.call(this);g.pp(this.element,"ytp-show-tiles");this.player.U().B?g.hp(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.AR(this.player,!1);u5(this)?(v5(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.j.select(!0):this.j.yC():this.videoData.autonavState===3&&this.j.wy()):(g.AR(this.player,!0),v5(this));a!==this.Hb&&this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var a=this.Hb;m5.prototype.hide.call(this);this.j.wy();v5(this);a!==this.Hb&&this.player.logVisibility(this.element,!1)};
g.k.Cca=function(a){a.target===this.element&&this.gr()};
g.k.gr=function(){var a,b,c,d;var e=((a=this.videoData)==null?0:(b=a.suggestions)==null?0:b.length)?(c=this.videoData)==null?void 0:c.suggestions:[(d=this.videoData)==null?void 0:g.nQ(d)];if(e.length){g.np(this.element,"ytp-endscreen-paginate");var f=this.J.Zn(!0,this.J.isFullscreen());if(a=g.nR(this.J))a=a.Hh()?48:32,f.width-=a*2;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;p>0&&(a<l||b<m);){var q=a/2,r=b/2,t=a<=l-2&&p>=r*n,u=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&u)p-=q*n,b+=2;else if(t)p-=r*n,a+=2;else if(u)p-=q*n,b+=2;else break}d=!1;p>=3*n&&c*n-p<=6&&(b>=4||a>=4)&&(d=!0);n=a*96;p=b*54;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.um(f,n,p);g.jm(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.tI(g.nQ(this.videoData));this.j instanceof
k5&&l5(this.j);g.rp(this.element,"ytp-endscreen-takeover",u5(this));v5(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,t=0,d&&l>=a-2&&m>=b-2?t=1:m%2===0&&l%2===0&&(m<2&&l<2?m===0&&l===0&&(t=2):t=2),q=g.Ed(q+this.C,c),t!==0){r=this.stills[h];r||(r=new s5(this.player),this.stills[h]=r,f.appendChild(r.element));u=Math.floor(p*m/b);var y=Math.floor(n*l/a),A=Math.floor(p*(m+t)/b)-u-4,D=Math.floor(n*(l+t)/a)-y-4;g.qm(r.element,y,u);g.um(r.element,D,A);g.jm(r.element,"transitionDelay",
(m+l)/20+"s");g.rp(r.element,"ytp-videowall-still-mini",t===1);g.rp(r.element,"ytp-videowall-still-large",t>2);t=Math.max(D,A);g.rp(r.element,"ytp-videowall-still-round-large",t>=256);g.rp(r.element,"ytp-videowall-still-round-medium",t>96&&t<256);g.rp(r.element,"ytp-videowall-still-round-small",t<=96);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.U(),u=g.mp(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",i5(r,q,u),g.IO(t)&&!r.api.L("web_player_log_click_before_generating_ve_conversion_params")&&
(t=q.El(),u={},g.iR(r.api,"addEmbedsConversionTrackingParams",[u]),r.api.L("embeds_web_enable_referring_feature_deprecation")||g.ZK(u,"emb_rel_end"),t=g.Ti(t,u),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.setTrackingParams(r.element,q));h++}f.ariaBusy="false";g.rp(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.pe(a.element),g.fb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData(1);this.videoData!==a&&(a!=null&&g.nQ(a)?(this.C=0,this.videoData=a,this.gr()):this.player.oa("missg",{vid:(a==null?void 0:a.videoId)||"",cpn:(a==null?void 0:a.clientPlaybackNonce)||""}))};
g.k.M4=function(){this.C+=this.stills.length;this.gr()};
g.k.N4=function(){this.C-=this.stills.length;this.gr()};
g.k.OZ=function(){return this.j.Il()};
g.k.nN=function(a){a===1?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.Oq(),this.Hb&&this.gr()):(this.G=!0,this.Hb&&u5(this)&&(a===2?this.j.yC():a===3&&this.j.wy()))};
g.k.L4=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.logVisibility(this.stills[a].element,!0);this.nN(1)}else this.D=null,this.G=!1;this.gr()};
g.k.Df=function(){return this.Hb&&u5(this)};g.z(w5,m5);w5.prototype.show=function(){if(this.player.getPlayerState()!==3){m5.prototype.show.call(this);var a=this.B;if(a){var b=this.j.suggestionData.length>0;g.rp(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;(c=g.nR(this.player))==null||c.qC(!0);this.player.logVisibility(this.element,!0);this.watchButton.Mc(!0)}};
w5.prototype.hide=function(){m5.prototype.hide.call(this);var a;(a=g.nR(this.player))==null||a.qC(!1);this.player.logVisibility(this.element,!1);this.watchButton.Mc(!1)};g.z(djb,g.XT);g.k=djb.prototype;g.k.wv=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((this.player.jd()||this.B)&&!b)return!0;var c;var d=!!((a==null?0:g.nQ(a))||(a==null?0:(c=a.suggestions)==null?0:c.length));d=!ajb(this.player)||d;a=a.Nj;c=this.player.bF();return d&&!a&&!c&&!b};
g.k.Df=function(){return this.endScreen.Df()};
g.k.e$=function(){return this.Df()?this.endScreen.OZ():!1};
g.k.xa=function(){this.player.rf("endscreen");g.XT.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.Bb().He.get("heartbeat"),d=g.nQ(a);!d||b.videoId!==d.videoId||a.oW?(this.player.qp(b.videoId,void 0,void 0,!0,!0,b),c&&c.VK("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.XT.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.XT.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.wv()&&(this.endScreen.created||this.endScreen.create(),a.getId()==="load"&&this.load())};
g.k.onCueRangeExit=function(a){a.getId()==="load"&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){cjb(this);this.D&&bjb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new o5(this.player):this.endScreen=new t5(this.player),g.P(this,this.endScreen),g.GR(this.player,this.endScreen.element,4))};g.WT("endscreen",djb);})(_yt_player);
