(function(g){var window=this;'use strict';var K5=function(a,b){g.T.call(this,{I:"button",Na:["ytp-miniplayer-expand-watch-page-button","ytp-button","ytp-miniplayer-button-top-left"],X:{title:"{{title}}","data-tooltip-target-id":"ytp-miniplayer-expand-watch-page-button","aria-keyshortcuts":"i","data-title-no-tooltip":"{{data-title-no-tooltip}}"},V:[{I:"svg",X:{height:"24px",version:"1.1",viewBox:"0 0 24 24",width:"24px"},V:[{I:"g",X:{fill:"none","fill-rule":"evenodd",stroke:"none","stroke-width":"1"},V:[{I:"g",X:{transform:"translate(12.000000, 12.000000) scale(-1, 1) translate(-12.000000, -12.000000) "},
V:[{I:"path",X:{d:"M19,19 L5,19 L5,5 L12,5 L12,3 L5,3 C3.89,3 3,3.9 3,5 L3,19 C3,20.1 3.89,21 5,21 L19,21 C20.1,21 21,20.1 21,19 L21,12 L19,12 L19,19 Z M14,3 L14,5 L17.59,5 L7.76,14.83 L9.17,16.24 L19,6.41 L19,10 L21,10 L21,3 L14,3 Z",fill:"#fff","fill-rule":"nonzero"}}]}]}]}]});this.J=a;this.listen("click",this.onClick,this);this.updateValue("title",g.xR(a,"Expand","i"));this.update({"data-title-no-tooltip":"Expand"});this.addOnDisposeCallback(g.vR(b.Re(),this.element))},bkb=function(a){g.T.call(this,
{I:"div",
S:"ytp-miniplayer-ui"});this.N=this.G=!1;this.player=a;this.T(a,"minimized",this.oh);this.T(a,"onStateChange",this.vea);this.T(a,"documentpictureinpicturechange",this.Jaa)},ckb=function(a){var b=a.player.qb().getPlayerSize().width,c=0,d=b;
a.player.L("web_cairo_modern_miniplayer")&&!a.N&&(c=12,d=b-24);g.kSa(a.progressBar,c,d,!1);g.BV(a.progressBar)},dkb=function(a){g.XT.call(this,a);
this.B=new g.OE(this);this.j=new bkb(this.player);this.j.hide();g.GR(this.player,this.j.element,4);a.isMinimized()&&(this.load(),g.rp(a.getRootNode(),"ytp-player-minimized",!0))};
g.z(K5,g.T);K5.prototype.onClick=function(){this.J.ib("onExpandMiniplayer")};g.z(bkb,g.T);g.k=bkb.prototype;
g.k.show=function(){this.j=new g.ep(this.S4,null,this);this.j.start();if(!this.G){this.tooltip=new g.jW(this.player,this);g.P(this,this.tooltip);g.GR(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.le=new g.LU(this.player);g.P(this,this.le);this.progressBar=new g.AV(this.player,this);g.P(this,this.progressBar);g.GR(this.player,this.progressBar.element,4);this.B=new g.T({I:"div",S:"ytp-miniplayer-scrim"});g.P(this,this.B);this.B.Ja(this.element);this.T(this.B.element,"click",this.A0);
var a=new g.T({I:"button",Na:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},V:[g.Vx()]});g.P(this,a);a.Ja(this.B.element);this.T(a.element,"click",this.XU);a=new K5(this.player,this);g.P(this,a);a.Ja(this.B.element);this.C=new g.T({I:"div",S:"ytp-miniplayer-controls"});g.P(this,this.C);this.C.Ja(this.B.element);this.T(this.C.element,"click",this.A0);var b=new g.T({I:"div",S:"ytp-miniplayer-button-container"});g.P(this,b);b.Ja(this.C.element);a=new g.T({I:"div",S:"ytp-miniplayer-play-button-container"});
g.P(this,a);a.Ja(this.C.element);var c=new g.T({I:"div",S:"ytp-miniplayer-button-container"});g.P(this,c);c.Ja(this.C.element);this.Y=new g.vV(this.player,this,!1);g.P(this,this.Y);this.Y.Ja(b.element);b=new g.uV(this.player,this);g.P(this,b);b.Ja(a.element);this.nextButton=new g.vV(this.player,this,!0);g.P(this,this.nextButton);this.nextButton.Ja(c.element);this.K=new g.cW(this.player,this);g.P(this,this.K);this.K.Ja(this.B.element);this.D=new g.T({I:"div",S:"ytp-miniplayer-buttons"});g.P(this,this.D);
g.GR(this.player,this.D.element,4);a=new g.T({I:"button",Na:["ytp-miniplayer-close-button","ytp-button"],X:{"aria-label":"Close"},V:[g.Vx()]});g.P(this,a);a.Ja(this.D.element);this.T(a.element,"click",this.XU);a=new g.T({I:"button",Na:["ytp-miniplayer-replay-button","ytp-button"],X:{"aria-label":"Close"},V:[g.ay()]});g.P(this,a);a.Ja(this.D.element);this.T(a.element,"click",this.Qba);this.player.L("web_cairo_modern_miniplayer")&&(a=new K5(this.player,this),g.P(this,a),a.Ja(this.D.element));this.T(this.player,
"presentingplayerstatechange",this.T4);this.T(this.player,"appresize",this.kc);this.T(this.player,"fullscreentoggled",this.kc);this.player.L("web_cairo_modern_miniplayer")&&this.T(this.player,"onPlaylistUpdate",this.kS);this.kc();this.G=!0}this.player.getPlayerState()!==0&&g.T.prototype.show.call(this);this.progressBar.show();this.player.unloadModule("annotations_module")};
g.k.hide=function(){this.j&&(this.j.dispose(),this.j=void 0);g.T.prototype.hide.call(this);this.player.isMinimized()||(this.G&&this.progressBar.hide(),this.player.loadModule("annotations_module"))};
g.k.xa=function(){this.j&&(this.j.dispose(),this.j=void 0);g.T.prototype.xa.call(this)};
g.k.XU=function(){this.player.stopVideo();this.player.ib("onCloseMiniplayer")};
g.k.Qba=function(){this.player.playVideo()};
g.k.A0=function(a){if(a.target===this.B.element||a.target===this.C.element)this.player.getPlayerStateObject().isOrWillBePlaying()?this.player.pauseVideo():this.player.playVideo()};
g.k.oh=function(){g.rp(this.player.getRootNode(),"ytp-player-minimized",this.player.isMinimized());this.player.L("web_cairo_modern_miniplayer")&&(g.rp(this.player.getRootNode(),"ytp-modern-miniplayer",this.player.isMinimized()),this.kS())};
g.k.Jaa=function(){g.rp(this.player.getRootNode(),"ytp-player-minimized",this.player.Dj());g.rp(this.player.getRootNode(),"ytp-player-document-picture-in-picture",this.player.Dj());this.kS()};
g.k.Cg=function(){this.progressBar.Tc();this.K.Tc()};
g.k.S4=function(){this.Cg();this.j&&this.j.start()};
g.k.T4=function(a){g.U(a.state,32)&&this.tooltip.hide()};
g.k.kS=function(){this.N=this.player.isMinimized()&&!!this.player.getPlaylist();g.rp(this.player.getRootNode(),"ytp-has-playlist-data",this.N);ckb(this)};
g.k.kc=function(){ckb(this)};
g.k.vea=function(a){this.player.isMinimized()&&(a===0?this.hide():this.show())};
g.k.Re=function(){return this.tooltip};
g.k.zy=function(a,b,c,d,e){var f=0,h=d=0,l=g.Am(a);if(b){c=g.mp(b,"ytp-prev-button")||g.mp(b,"ytp-next-button");var m=g.mp(b,"ytp-play-button"),n=g.mp(b,"ytp-miniplayer-expand-watch-page-button");c?f=h=12:m?(b=g.tm(b,this.element),h=b.x,f=b.y-12):n&&(h=g.mp(b,"ytp-miniplayer-button-top-left"),f=g.tm(b,this.element),b=g.Am(b),h?(h=8,f=f.y+40):(h=f.x-l.width+b.width,f=f.y-20))}else h=c-l.width/2,d=25+(e||0);b=this.player.qb().getPlayerSize().width;e=f+(e||0);l=g.Dd(h,0,b-l.width);e?(a.style.top=e+"px",
a.style.bottom=""):(a.style.top="",a.style.bottom=d+"px");a.style.left=l+"px"};g.z(dkb,g.XT);g.k=dkb.prototype;g.k.onVideoDataChange=function(){if(this.player.getVideoData()){var a=this.player.getVideoAspectRatio(),b=16/9;a=a>b+.1||a<b-.1;g.rp(this.player.getRootNode(),"ytp-rounded-miniplayer-not-regular-wide-video",a)}};
g.k.create=function(){g.XT.prototype.create.call(this);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.onVideoDataChange()};
g.k.jn=function(){return!1};
g.k.load=function(){this.player.hideControls();this.j.show()};
g.k.unload=function(){this.player.showControls();this.j.hide()};g.WT("miniplayer",dkb);})(_yt_player);
